### ISSUE TITLE
Install fails on Ubuntu 14.10: cannot find header files for ruby

### ISSUE THREAD

**Issue by ellipticview** [gollum/gollum#1005]
I followed the instructions for 14.04 on the install page. The first command (sudo apt-get install) is successful. The second command fails:
```
ubuntu@ubuntu-amd64:~$ sudo gem install gollum
Fetching: github-markup-1.3.3.gem (100%)
Successfully installed github-markup-1.3.3
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gollum:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out
```

**Comment by SkyCrawl** [comment]
This is most definitely not a problem of Gollum :). Your environment complains it cannot compile a native extension and you can see for yourself that the required files are **outside** of anything Gollum-related.

To resolve this issue, try googling. E.g.:
<http://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby>

**Comment by ellipticview** [comment]
Well, there does seem to be an issue in the installation documentation.
I solved this issue by:
```
sudo apt-get install ruby-dev
```
but this does leave me wondering: the installation page already has ruby1.9.1 and ruby1.9.1-dev. Does ruby-dev replace these? Or does it simply need to be added?

**Comment by SkyCrawl** [comment]
> the installation page already has ruby1.9.1 and ruby1.9.1-dev.

I'm no Ruby installation/distribution expert but I think this issue is related to it. Your Ruby installation (again... in my opinion) simply lacked something. In my little experience, this is most often the case if you install:
* unofficial Ruby implementations (something other than MRI),
* implementations from "unofficial" sources such as package managers.

What I don't understand at all is your reference to Ruby v1.9.1. The error message you provided above contains:
* `/usr/bin/ruby2.1`
* `/var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/`

which most definitely refers to Ruby v2.1.0 :).

**Comment by dometto** [comment]
@ellipticview, the installation guide in the wiki is pretty much user-maintained. If you find any additional pages are necessary, it's much appreciated if you edit the wiki accordingly. :) In this particular case I indeed think that the issue is with the fact that your ubuntu install is using ruby 2.1 (maybe that's the new default), so that `ruby-dev` is necessary instead of its older `1.9` brother.
