### ISSUE TITLE
Question? Bug? regarding handling of Markdown links

### ISSUE THREAD

**Issue by firecat53** [gollum/gollum#1011]
Greetings...new Gollum user for the last few days...thank you! I'm not sure if this is more a bug report or question.

One of the selling points of Gollum is editing the wiki via command line...perfect! However, the links get manipulated by Gollum such that I can't take a copy of my wiki and use it with other Markdown viewers.

Example 'real' file structure:

    /Home.md
    /diary
    /diary/diary-index.md

A 'normal' Markdown link would be

    [diary](diary/diary-index.md)

Trying to create a _new_ page from that link results in a file named diary/diary-index-dot-md.md. Trying to click that link when there is an existing file at diary/diary-index.md results in my browser (Firefox) opening a download dialog for the file.

The link works fine as `[diary](diary/diary index)` or `[[diary|diary index]]`, but neither of those are portable link formats.

Is this expected behavior and this is a 'wontfix' type item or is it a possible enhancement? Are there workarounds?

Thanks very much for your time!
Scott

**Comment by dometto** [comment]
> Is this expected behavior
Yes, this is a feature, which derives from the fact that gollum supports multiple markups -- it allows you to link to pages without knowing the syntax the page is written in, or the full filename. I realize this can be annoying for some use cases. Not sure what a good workaround would look like; one possibility would be a command line option that modfies the page routing logic so that it ignores valid page extensions in the request path. PR's would be welcome.

**Comment by bartkamphorst** [comment]
@firecat53 It might also be helpful to know that gollum differentiates between _pages_ and _files_. And page names are referenced without a file extension. If your markdown link contains a file extension like in your example (`diary-index.md`), gollum will look for a page called `diary-index-dot-md`, and when it cannot find that, it will look for a file with the name `diary-index.md`. If it does find that file, it will offer it up as a downloadable file instead of rendering the content.
