### ISSUE TITLE
Document how to deploy to Heroku

### ISSUE THREAD

**Issue by aviflax** [gollum/gollum#1013]
I’d like to try Gollum out but I don’t quite get how to make it work on Heroku. Everything I’ve found via Google seems potentially out-of-date.

**Comment by aviflax** [comment]
Now that I think about it, I don’t really see any docs about deployment. There’s something about “installation” in the readme but I’m not sure how that fits in with deployment — I’m not familiar with Ruby apps and I just don’t have a mental model on how to deploy Gollum — in particular the relationship on the filesystem between the app files and the wiki data/repo. Can they live together in the same dir? Would that be good, or bad?

**Comment by SkyCrawl** [comment]
Hello @aviflax ,

> I’d like to try Gollum out but I don’t quite get how to make it work on Heroku.

if you'd like to try Gollum out, the easiest way is to use it "as is" locally, without any deployment whatsoever. For that, all information you should need can be read in README.

> I’m not familiar with Ruby apps and I just don’t have a mental model on how to deploy Gollum, in particular the relationship on the filesystem between the app files and the wiki data/repo.

It's actually quite simple. Gollum can be thought of as a system library that you install with `gem install gollum` (perhaps also with `sudo` sometimes). As such, it should be installed into a "system-managed" directory, outside of where the users usually operate (including the "wiki data/repo", in your case).
Then, opening a CLI and executing a command like `gollum [options]` tells Gollum to treat the current working directory of the CLI as a wiki data/repo. It fails when the directory **IS NOT** a git repository as Gollum is a git-based Wiki. And when the directory **IS** a git repository, Gollum will serve it to any HTTP requests with the `4567` (by default) port, e.g. `http://localhost:4567`. That includes remote access, e.g. `http://my-wiki-domain:4567`.

> Now that I think about it, I don’t really see any docs about deployment.

That is probably because Gollum is mostly meant as a personal wiki. Most people seem to use it locally on their computers, they launch and stop Gollum when they need to do it. I'm not sure whether you're entirely familiar with what deploying your Gollum wiki to Heroku means:
* It's highly likely that anyone will be able to access/edit your wiki since (as far as I know) Gollum doesn't yet offer user-control.
* Controlling Gollum will very likely be more complicated because it's a remote "server".

That should be enough to get you started on understanding what Gollum is. What it offers and how it behaves, you should discover for yourself by trying it out :).

Now onto deployment on Heroku. At the moment, I don't have time to investigate this in detail but hopefully, it could be very similar to running Gollum locally:

1. Install the gollum gem on your Heroku "server".  
If that can not be done, [this tutorial](https://devcenter.heroku.com/articles/getting-started-with-ruby#introduction) should be all you need to know. However, in such a case you'd need to follow the tutorial 3 times: once for Gollum, once for Gollum-lib and once for a git backend, e.g. Grit-adapter. All of them are hosted here on GitHub. Also, the Ruby `require` directives would probably have to be changed (or circumstances altered)... I'm no expert on that.
2. Create your wiki's git repository, initialize it and deploy it on Heroku somehow, perhaps using the information [here](https://devcenter.heroku.com/articles/git).
3. Then it's all about executing the `gollum [options]` command remotely on Heroku.

---

If you have further questions, feel free to ask.

**Comment by dometto** [comment]
There is a rudimentary, user-maintained, install guide [in the wiki](https://github.com/gollum/gollum/wiki/Installation). If someone gets gollum running on heroku, please share your info there. :)

**Comment by SkyCrawl** [comment]
@aviflax 

For the sake of completeness... when it comes to deploying your Gollum wiki to a remote server accessible from anywhere, I think [koding](https://koding.com/) could be a better (**but most importantly simpler to use**) option :).

Gollum installation is plain simple there, as well as creating a git repository and letting Gollum serve it. It's practically the same as doing it locally.

The only downside is that the free version of their service turns your VM off when it is inactive.

**Comment by aviflax** [comment]
@SkyCrawl and @dometto: thanks **so** much for all the super-helpful info! I really appreciate it!
