### ISSUE TITLE
TOC erroneously renders <> as HTML tag from backtick'd titles

### ISSUE THREAD

**Issue by Bob131** [gollum/gollum#1018]
If the following is added on a page with the `[[_TOC_]]` directive:
```
# `Test <text>`
```
the following appears in the HTML:
```
<ul><li><a href="#test-text">Test <text></text></a></li></ul>
```
Which gets rendered by Firefox as "Test"

**Comment by SkyCrawl** [comment]
> TOC erroneously renders <> as HTML tag

Yes, that is a bug indeed :).

@dometto 
I think (not completely sure) that nothing bad would happen if sanitization filter is the last processed action in the filter chain (after TOC, that is)?

**Comment by Bob131** [comment]
@SkyCrawl 
Formatting titles with entity codes alleviates the problem in the TOC as expected, but since the title itself is wrapped in a &lt;code> tag the `&lt;` is rendered as literal instead of the entity. Hence this bug report

**Comment by SkyCrawl** [comment]
@Bob131 
Yes, I know :). That's why the `# Test &lt;text&gt` syntax I suggested has no backticks (hence doesn't render into a code tag). I'm curious as to why you want to wrap your headers in a code tag? From my point of view, I can't see a good reason :).

**Comment by Bob131** [comment]
We find it beneficial to use monospaced headings to document things like configuration references, for better readability. Simply wrapping the title contents in backticks is far more practical to achieve this than trying to get Gollum to parse Kramdown-style tag attributes since I personally aren't familiar enough with Ruby and its infrastructure to be able to coax Gollum into reliably producing the result I desire.

Even so, I'm of the opinion that using backticks is syntactically preferable to adding tag attributes to near every header in an entire document when its not a necessity.

**Comment by Bob131** [comment]
Another issue I've just now noticed, in a very similar vein, is the lack of escaping in &lt;pre> tags denoted with Kramdown-style tildes (`~~~`):

    ~~~
    SECRET: <your secret>
    ~~~

becomes

    <pre>SECRET: <your secret=""></pre>

**Comment by dometto** [comment]
Are you sure kramdown normally escapes those <'s in a three tilde block? Can't think of a reason why this would be omitted in gollum.

**Comment by Bob131** [comment]
Just tried it in Jekyll using the kramdown engine, it seems to take the extra step of wrapping the contents of the &lt;pre> tag in a &lt;code> tag so that it renders properly.

**Comment by dometto** [comment]
In that case just use four tildes for github-style code blocks. :) I think its probably not doing the same for the three tilde syntax because gollum uses kramdown in github-mode.

**Comment by SkyCrawl** [comment]
> We find it beneficial to use monospaced headings to document things like configuration references, for better readability.

Thank you, I understand better now :).
I have no intention of forcing you a different view/solution but if you're interested:

I can see the point of using TOC as a "quick reference" (a shortcut for having to make something like that yourself) for various things but in your case, it's closer to "abusing" TOC in my mind.
The problem with TOC is that:
* It's not (at the moment, anyway) really made to support these things.
* Using HTML-tagged headers probably imposes CSS problems since the TOC will likely turn into a "mosaic". The `<a>` tag is not really suited to having nested HTML tags :).

While it's certainly nice to have the most important information grouped in the TOC, I don't think it enhances readability all that much (in general). Especially given that I don't remember seeing something like that ever before :).
Should you have the "syntax" indexed by TOC or (for example) custom tables meaningully categorized by TOC, it's about the same thing. Except that using tables gives you much more readability if you need to compare the "syntax" or construct a more detailed overview of it. A TOC entry can only include a very limited amount of information and if you "waste" it for something "unmeaningful", readability goes down by a lot :).

**Comment by Bob131** [comment]
>I have no intention of forcing you a different view/solution but if you're interested:

Honestly, not really. I appreciate you don't think this use case is valid or "correct", but advice on such matters is not why I'm here.

**Comment by dometto** [comment]
> In that case just use four tildes for github-style code blocks. :)

I think that should be a good workaround -- if not please reopen.
