### ISSUE TITLE
Improve the --version switch to provide relevant gem names with versions

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1022]
``` sh
$ gollum --version
Gollum 4.0.0
Gollum-lib 4.03
Grit-adapter 1.0.0
With the following renderers:
Kramdown 1.6.0
[...]
```

Alternatively we could add a specific `--renderers` flag to list available rendering gems.

**Comment by dometto** [comment]
Playing around a bit with this:
```ruby
  opts.on("--version", "Display current version.") do
    puts "Gollum " + Gollum::VERSION
    require 'gollum-lib'
    puts "Gollum-lib " + Gollum::Lib::VERSION
    adapter_name = defined?(Gollum::Git::ADAPTER_NAME) ? Gollum::Git::ADAPTER_NAME : "unknown"
    adapter_version = defined?(Gollum::Git::VERSION) ? Gollum::Git::VERSION : "unknown"
    puts "Git adapter: #{adapter_name}, version #{adapter_version}"
    exit 0
  end
```
However, some problems:
* the git adapters don't require their `version.rb` file, so the `VERSION` constant for the adapters is not set when gollum-lib is required
* the git adapters currently define their version under `Gollum::Lib::Git` rather than under `Gollum::Git`
* the git adapters currently don't have an `ADAPTER_NAME` constant
* Getting the available rendering gems is non-trivial. Currently, the way support for a given markup is checked is just by trying to render the page and rescuing a `LoadError` if necessary. We would have to:
  * Determine which registered markups use which `GitHub::Markup` class
  * then try to call that class's `load` method (see [here](https://github.com/github/markup/blob/master/lib/github/markup/gem_implementation.rb#L14-L18)] (Ideally, `github-markup` would have a method doing this)

**Comment by SkyCrawl** [comment]
> Improve the --version switch to provide relevant gem names with versions

Great idea :).

> Alternatively we could add a specific --renderers flag to list available rendering gems.

> Getting the available rendering gems is non-trivial.

To me, personally, this seems a feature more suited for `github-markup`, at least in part. If it were me, I'd try to do the following:

1. Finish [this PR](https://github.com/github/markup/pull/494#issuecomment-110848867), just like the guys say (a task for me since it is my PR).
2. Once that's done, `github-markup` will provide markup constants for all supported markups. With that, it shouldn't be difficult to make another PR which defines publicly available lists of gem names that are searched for when rendering (for each markup constant of course).
3. And from there, it's a tiny bit left to:
   * take the appropriate gem name list for each markup,
   * and cal `gem list --local | grep -i {gem-name}` [from inside Ruby](http://stackoverflow.com/questions/3159945/running-command-line-commands-within-ruby-script).

**Comment by techwiz24** [comment]
@SkyCrawl regarding the `Windows` con: Does gollum support windows now? I wasn't aware of that.

@bartkamphorst @dometto I was just going to file this after mentioning it in #907, thanks for adding the issue / feature request!

**Comment by SkyCrawl** [comment]
Well, I'm not sure since when has Gollum started to support WIndows (I always thought that only the default grit adapter didn't work on Windows for some reason). But as far as I know, with rjgit adapter, Windows should now be supported although rigorous testing is needed.

**Comment by dometto** [comment]
> as I know, with rjgit adapter, Windows should now be supported although rigorous testing is needed.

That's right. Rigorous testing has not happened until now because I don't have Windows. :) Does require java though. Rugged should technically be able to run on Windows since it's based on libgit2, but I think in practice it's not fully functional yet. Would also be nice to test though.

@SkyCrawl: good roadmap, as I said this would ideally be part of github-markup. So let's try to get it in there. :+1:

> is there a nice alternative for gem list --local | grep -i {gem-name} in Windows, 

Maybe we don't need to grep but could just try to require the gem?

>  Do we need it for development though?

Mainly I think this feature should be for end users, so that filing bug reports will be easier.

**Comment by techwiz24** [comment]
> That's right. Rigorous testing has not happened until now because I don't have Windows. :) Does require java though. Rugged should technically be able to run on Windows since it's based on libgit2, but I think in practice it's not fully functional yet. Would also be nice to test though.
> -- @dometto 

Huh, I'll have to see if I can get procurement to get a copy of jruby for me, I'll be glad to help test this! Thanks for the info!

**Comment by bartkamphorst** [comment]
@techwiz24 Cool! Looking forward to hearing about your experiences.

**Comment by bartkamphorst** [comment]
Okay, so let's start with the low-hanging fruit and improve `--version` by having it output gollum-lib's version and the git adapter version. We can wait with implementing the `--renderers` flag until @SkyCrawl 's proposed changes in github-markup have made it through. I wonder if there is any robust way of inspecting Gollum::Lib::VERSION without requiring the gollum-lib gem in its entirety though. Any thoughts on that?

**Comment by techwiz24** [comment]
@bartkamphorst What did you mean by "without requiring the gollum-lib gem in its entirety". Do you mean you want to be able to get the version without an explicit `require`, or you want to be able to get the version without having all of the gem installed?

If you want to do it without `require`-ing the gem, I think you can do something like this:

```ruby
gollum@wikitest:~$ irb
irb(main):001:0> Gem.latest_spec_for('gollum').version.to_s
=> "4.0.0"
irb(main):002:0> Gem.latest_spec_for('gollum-lib').version.to_s
=> "4.0.3"
```

Although that just pulls the latest version installed (I don't know if you guys have ever pinned versions or not).

**Comment by SkyCrawl** [comment]
@techwiz24 

> If you want to do it without require-ing the gem, I think you can get it from the gem by doing something like this. Although that just pulls the latest version installed (I don't know if you guys have ever pinned versions or not). There's also Gem::Specification.all() if you want the shotgun approach...

Idd, nice summary. Personally, I'd avoid the command line solution in this case because of the version issue and irrelevance.

Also, I already utilized the gemspec solution in my forks for various reasons. Mostly I meant to replace the current solution of "hardcoding the gem's version into the code" with this:

```
# Helpers querying gemspec for information.
    module Gemspec
      GEMSPEC_FILE_PATH = Dir["#{ROOT_FOLDER}*.gemspec"].first
      GEM_SPEC_CURRENT = Gem::Specification::load(GEMSPEC_FILE_PATH)
      
      def self.gemspec_filename
        GEMSPEC_FILE_PATH.split('/').last 
      end
          
      def self.gem_name
        gemspec_filename.split('.').first
      end
          
      def self.gem_version
        GEM_SPEC_CURRENT.version
      end
    end
```

Then `Gollum::Helpers::Gemspec.gem_version` takes the current gem's version from gemspec and outputs it, regardless of `Gem.latest_spec_for('gollum-lib').version.to_s `. It's a completely self-sufficient system that also respects the gemspec constraints of consumer gems.

@bartkamphorst 

> I wonder if there is any robust way of inspecting Gollum::Lib::VERSION without requiring the gollum-lib gem in its entirety though. Any thoughts on that?

Although in my forks, the above module/methods are located in the `utilities.rb` file, we could also outsource the module/methods into a (e.g.) `gollum/version.rb` in which case you would need to:
* require `gollum/version`
* call (e.g.) `Gollum::Gemspec.gem_version`

@dometto 

> Maybe we don't need to grep but could just try to require the gem?

Maybe but the original idea was to collect the gems' versions. As far as I know, there's no uniform way to do that by just requiring the gems? Correct me if I'm wrong, please :).
Hmm, perhaps there could be a way using the above mentioned approach but is it necessary or efficient to go that far for rendering gems?

**Comment by bartkamphorst** [comment]
> Maybe but the original idea was to collect the gems' versions. As far as I know, there's no uniform way to do that by just requiring the gems?

I think the idea was that if require would return true then you could check for a VERSION constant within the gem's namespace (e.g., Kramdown::VERSION). Not sure how robust that would be though.

> Do you mean you want to be able to get the version without an explicit require, or you want to be able to get the version without having all of the gem installed?

@techwiz24 I had the former in mind. It just seems a little wasteful to require a bunch of gems only to get the version and subsequently exit. Basically I was thinking of following `require`'s logic for traversing `$LOAD_PATH` and only evaluating `lib/<gemname>/version.rb` of the gems we are interested in (gollum-lib + git adapter). And if multiple versions would be installed I would want to find the same versions of the gems that `require` would find.

**Comment by SkyCrawl** [comment]
> I think the idea was that if require would return true then you could check for a VERSION constant within the gem's namespace (e.g., Kramdown::VERSION). Not sure how robust that would be though.

Yes, the idea was to find out the gem's version :). Although this approach is certainly nice and works for some gems, I don't think it works for all gems, especially since the namespace is typically different for each gem. The approach I mentioned (`gem list --local`) works for all gems but disregards gemspec constraints...

Maybe we could mix these approaches? E.g. require a gem and if it works, find out its absolute location and load its gemspec?

**Comment by dometto** [comment]
This may be less difficult than we supposed:
```ruby
  puts Gem.loaded_specs.map {|k, v| v.to_s}
```
Returns:
```
#<Gem::Specification name=rake version=10.5.0>
#<Gem::Specification name=i18n version=0.8.1>
#<Gem::Specification name=multi_json version=1.1
...
```
(including gollum-lib and the adapter)

**Comment by bartkamphorst** [comment]
Terrific! 👍

**Comment by bartkamphorst** [comment]
This has been implemented in https://github.com/gollum/gollum/commit/92e42236f57e4e8183172a49edc02c38eee5b87e (in the 5.x branch).
