### ISSUE TITLE
Feature request: add redirect support

### ISSUE THREAD

**Issue by roccomoretti** [gollum/gollum#1023]
Currently, if you go to a URL which corresponds to a page which does not exist, Gollum pops up a "Create New Page" page. It would be nice to be able to override this behavior, and have selected pages redirect to other pages.

How I envision it is that there would be something like an optional "_Redirect" file which contains pairing of "source" and "target" names. This facility would only be triggered if the standard page resolution machinery failed. (That is, insert the _Redirect check right before the "Create New Page" launch.) If the requested source path is listed in the _Redirect file, the corresponding target path would be used instead. (For example, with a 301 or 307 http redirect.) If the requested path isn't listed, then the standard "Create New Page" page is shown for the original path.

This is somewhat related to issues  #516 and #565 but is different in that it is not rename-specific, instead proposing a mechanism which can handle arbitrary redirects. (The rename feature could be somewhat compatible with this feature by adding a line to the _Rename file for page moves done through gollum. Page moves done externally would require manual fixing, though.)

**Comment by SkyCrawl** [comment]
So, if I understand correctly, in the end you are suggesting for Gollum to implement user-defined page aliases? E.g. `/wiki/my-non-existing-page-and-defacto-a-page-alias` will translate (and redirect) into `/wiki/my-existing-page`.

Definitely a feature worth some thought but personally, I seem to struggle to find a good use-case for it. Could you please provide one from your perspective? :)

**Comment by roccomoretti** [comment]
@SkyCrawl Yes, that's another way to look at it, though I'd like some support of directory structure in it too, so `/wiki/subdir1/subsubdir1/page-alias` could point to a different location than `/wiki/subdir2/page-alias`, rather than aliases being confined to the flat namespace.

The main use case I'm looking for is preserving URLs. We've done a reorganization of our gollum wiki site, which involved merging, moving and renaming pages.  We also switched the public site from a static gollum-site version (which had a flat layout) to a no-edit gollum version (which has a nested directory structure). This means that all the old URLs we had aren't working anymore. I'd like to be able to set up redirects so that people who have an old URL can still be directed to the appropriate page, rather than being given a 404. (Actually, worse - a "Forbidden. This wiki is set to no-edit mode" error.)

I'm looking for a manual approach rather than the automatic ones suggested in the other issues because some of the redirects involved multi-page merges rather than page moves, and also because git move detection can be flaky sometimes, and doesn't necessarily recognize that a page was moved. ("skipping inexact rename detection" and all that.)

**Comment by SkyCrawl** [comment]
> though I'd like some support of directory structure in it too

Yes, I had the same in mind. Sorry for not making it clear :).

Thank you, now I see your point of view. Your proposed feature is probably shadowed by a find/replace feature then, because redirecting existing URLs on the client side is only a part of any large reorganizations. Sometimes, only the find/replace may be "necessary" (rather convenient) to correctly update inner links :).

As for the solution, I'm afraid that:
* we're too short on hands and time,
* we have too many issues on our hands.

But you may still be able to almost fully achieve what you propose in case you know somebody Ruby capable who could experiment a little:

1. The first step is to override the [before method in Precious::App](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L95) since it is (as far as I can see) currently the best piece of code to experiment with for the feature. I doubt this would be possible without extending the `Precious::App` class :).
2. Integrating the extended class into Gollum, either through the [bin script](https://github.com/gollum/gollum/blob/master/bin/gollum#L219) or custom [rack configuration](https://github.com/gollum/gollum#rack).

Arguably, the rack configuration seems to be the easier and more suitable way as the `bin` script is not designed for such "hacks". But with a tiny PR, it should be a feasible way too if Gollum's [configuration file](https://github.com/gollum/gollum#config-file) was to be used :).

@dometto @bartkamphorst 
Any idea whether file symlinks could resolve the issue, however inconvenient they might be in this case?

**Comment by dometto** [comment]
I think implementing support for symlinks would go some way to implementing this feature, but of course it wouldn't redirect to the targeted page, but just display its contents. Redirecting requires hacking Precious::App whether we use symlinks or some other kind of file to specify the urls.

**Comment by TallTed** [comment]
Reinventing wheels should come much closer to an approximation of a circle than a square.  Redirects and/or "page moved" are basic features of every wiki in wide use.  Why does Github's "better than the others because we made it" wiki not support these basic features?

**Comment by dometto** [comment]
@TallTed gollum is not the engine running GitHub wikis (it used to be, but the two have diverged). We're a volunteer-run open source project and although redirect support would be great, we have limited support. Anyone is welcome to submit a PR with this future for the upcoming `5.x` release though. Be sure to hack away at, and submit the PR to, the `5.x` branch.

The simplest way I can see of doing this in `5.x` is using YAML frontmatter: the user could set e.g. `redirect: /new_page.md`, and after parsing the YAML, gollum could then execute the redirect. The rename function could easily change the old page to contain only this YAML keyword. The downside is this is not super efficient, since the old page has to be loaded and rendered before the redirect is executed (even if it only contains the YAML block).

**Comment by bartkamphorst** [comment]
> The simplest way I can see of doing this in 5.x is using YAML frontmatter: the user could set e.g. redirect: /new_page.md, and after parsing the YAML, gollum could then execute the redirect.

I actually think this is a fairly elegant solution. In terms of efficiency, we could try to break out of the current filter_chain if a `redirect` key is found in the YAML. Since the YAML filter is the first filter, we might be able to temporarily remove/skip (most of) the other filters in the chain and gain a little speed that way. How would we trigger the redirect? Through jquery once the page is loaded? Or do you see some other, quicker way?

**Comment by dometto** [comment]
I guess one other way would be to raise an exception from the YAML filter in case a redirect is found, and catch that in Sinatra app... but not sure about using exceptions for application flow in this way.

**Comment by roccomoretti** [comment]
I'll remark that a YAML frontmatter filter wouldn't necessarily be 100% ideal for the original use case that prompted this feature request. In that situation there was a large reorganization of where a fair number of pages were moved. Requiring a stub file with just the redirect key at the original location would work on the web-facing side, but would still clutter the directory structure. 

It's better than nothing, so certainly don't stop any implementation on that regards, but I thought I should mention it as a consideration.

**Comment by bartkamphorst** [comment]
@roccomoretti Thanks for your input; I hadn't considered the resulting clutter. Perhaps we could have a yaml file on disk (and loaded in memory) containing a hash of redirects? That way the file could be updated via a `rename` action or externally (manually or with some scripting). The potential downside of this approach is the additional lookup operation that will need to be performed for every request. The hash will be in memory though, and with a relatively small set of redirects the overhead shouldn't be too bad. What do you think?

**Comment by bartkamphorst** [comment]
>  the additional lookup operation that will need to be performed for every request

Actually, this could be mitigated by only performing a redirect lookup if we encounter a `page not found`.

**Comment by dometto** [comment]
I like the idea, but wouldn't we have to re-read the YAML file every time there's a 404, because it may have been updated in the meantime?

**Comment by bartkamphorst** [comment]
Have a look at [YAML::Store](https://docs.ruby-lang.org/en/2.4.0/YAML/Store.html) (and [here](https://www.krautcomputing.com/blog/2015/09/21/rubys-built-in-databases-meet-pstore-and-yamlstore/)).

**Comment by dometto** [comment]
Looks great, but how would that interact with git? Or is the idea to not store the YAML file in the repo for simplicity's sake?

**Comment by bartkamphorst** [comment]
We could have the store be a dotfile in the wiki's root directory called `.redirects.gollum`. This would have to be a protected file. The rename action could commit the file to the git repository when a transaction is finished. If we want git to play a central role, though, we would incur some costs because we would have to
1. perform a `git checkout` on `.redirects.gollum` before opening the store (before each lookup).
2. load the contents of the store and perform our lookup operation.
3. close access to the store after each transaction.
4. commit the store to the repository.

It feels a little clumsy, but I'm not sure by what degree the performance will suffer because of this.

**Comment by dometto** [comment]
There's also the bare repo usecase to consider, so unless we have the file outside the repo altogether all read/write operations would have to go via git. But the performance impact would hopefully be minimal, since it would only occur on 404s. We could also implement some smart caching (invalidating the cache when the redirect file has been touched)

**Comment by roccomoretti** [comment]
Having a single file in the root directory with a list/hashmap of redirects sounds good - it's along the same lines as I was originally thinking when I posted this feature request.

I agree that, assuming you only query it when you don't otherwise have a page, the performance hit should be acceptable. I'd much prefer to have a slow load of an actual content page than a quick load of a 404/create page.

**Comment by bartkamphorst** [comment]
This functionality has been implemented in the 5.x branch.
