### ISSUE TITLE
Including source files on reStructured

### ISSUE THREAD

**Issue by renich** [gollum/gollum#1039]
Hello,

Please, consider this

```rst
Some title
##########

.. code-block:: bash
    :include: src/sample.rb
```

When I try rst2pdf, it includes it and does syntax highliting. On gollum, it doesn't work.

**Comment by SkyCrawl** [comment]
Hello @renich 

I think the culprit is [here](https://github.com/github/markup/blob/master/lib/github/commands/rest2html). Gollum uses the `github/markup` gem to do most of the rendering and `github/markup` seems to manually disable syntax highlighting for ReST files - see the reference above. I honestly don't know why it is disabled, whether it is necessary, pointless or simply unimplemented.

It is probably best to kindly redirect you to [github/markup](https://github.com/github/markup), where you can open an issue like this and ask:
* if syntax highlighting is disabled for a reason,
* for somebody to enable/implement it,

should you wish to do so :).

**Comment by renich** [comment]
I am sorry for not being precise. When I wrote "it doesn't work", I meant the files don't get included. I can attach a test case if you like.

**Comment by SkyCrawl** [comment]
Ah, right... sorry :(. Should have noticed the include...

> I can attach a test case if you like.

No need to do that, thank you. I can see why it doesn't work :).
As far as I know, Gollum's philosophy is not to handle cases like these, because it provides its own [include directive](https://github.com/gollum/gollum/wiki#include-other-pages), despite it only includes existing Gollum pages (not general files) :(.

Although small and slow steps are already being taken to fix the fact that include only works with pages, I can't see Gollum including files on the basis of `:include: src/sample.rb` anytime soon, since it is a part of a much larger endeavour for us :(. Unification of Gollum's own means and the means of each markup might actually be quite untrivial in some cases...

I'm afraid you would probably have to do this yourself. Should you wish to do so, I can get you started fast and well:

1. Fork [gollum/lib](https://github.com/gollum/gollum-lib).
2. Navigate to `gollum-lib/lib/gollum-lib/filter/`.
3. Create a new filter class/file. You can copy the basic structure of a filter from the others (`extract` and `process` methods are required). To implement the methods, I suggest to:
   * read the comments [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter.rb),
   * take inspiration from [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/tags.rb#L100).
4. Once you're done, you must add your newly created filter in [this hash](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/wiki.rb#L251), at the appropriate place.
5. And then you only need to integrate your forked `gollum/lib` into Gollum :).

**Comment by renich** [comment]
Hey man, sorry for taking so long to respond.

OK, I understand. Thanks a lot for the guide on how to accomplish this. I'll try to do this; if I can find the time and will to do it.

Feel free to close this ticket.

**Comment by renich** [comment]
BTW, this method should be published in the wiki or something.

**Comment by dometto** [comment]
It's in the wiki [here](https://github.com/gollum/gollum/wiki#include-other-pages), but yeah, the docs could be a lot more structured/transparent.
