### ISSUE TITLE
[Windows] - Page Title incorrect

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum#1041]
``` powershell
~$ jruby --version
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_51-b16 +jit [Windows 8.1-amd64]
```

Page titles are prepended with `://`:

![image](https://cloud.githubusercontent.com/assets/794251/9011343/be21a712-377a-11e5-93b6-e8c8a6277797.png)

![image](https://cloud.githubusercontent.com/assets/794251/9011334/b3dbed1c-377a-11e5-8673-21c7848cf912.png)

**Comment by nlowe** [comment]
I left a comment on the meta issue (https://github.com/gollum/gollum/issues/1044#issuecomment-425673170), sorry. I couldn't even get gollum running on windows. I can make a separate issue if you want?

To be honest, I haven't used gollum in over 2 years since I moved off the team that was using it. For windows, a docker container may be a better solution.

**Comment by dometto** [comment]
@nlowe there's an issue with sprockets, which was just introduced in 5.x, and Windows. You can work around the issue by using g gollum with static assets:
`gollum --static --assets path/to/public/assets`
...which is what @bartkamphorst used to get around the problem you reported in the meta-issue. A lot (or all) of the Windows specific, utf8 and filename based issues seem to be solved once you get around the assets problem. If you're still interested in confirming that for us, that would be great. I can upload the pre-compiled assets to a branch tomorrow.

(In the end, the assets issue wouldn't be a problem, because gollum would use pre-compiled assets out of the box.)

**Comment by nlowe** [comment]
Unless I need a valid assets path (if so where should I look for that?) It doesn't seem to improve anything, I'm seeing the same exact behavior (Some weird / corrupted exception from Execjs)

**Comment by dometto** [comment]
@nlowe yes, you need to have the right assets. Normally you could generate them yourself with `gollum --precompile`, but that's affected by the same bug on Windows. Until that's fixed (or we just distribute the assets with gollum and run it in production mode standardly), you can download the assets here: https://github.com/dometto/gollum_assets

Make sure to `git pull` the latest version of `5.x` as I've now pointed the `Gemfile` to the latest `gollum-lib` version (on GitHub `master`).

Then everything should run fine with `gollum --static --assets /path/to/assets/public`.
