### ISSUE TITLE
Users?

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum#1049]
Does Gollum have anything to support user registration of some sort? Atm if I were to make a wiki public then anyone could edit without any sort of authentication and the author would always be the same to Gollum. How does this work? Is there any documentation on the topic?

Ironically I find myself googling a lot of these questions for Gollum, the current documentation is very sparse.

**Comment by dometto** [comment]
There's nothing in the docs about this because gollum doesn't have any user/authorization support. :-) The is, however, a `session[gollum.author]` key that sets the name for commits and such.

Gollum is just a rack app, so you can put any bit of authentication and authorization middleware you want in front of it. Some examples:
* [omnigollum](https://github.com/arr2036/omnigollum)
* @dekimsey's comment  [here](https://github.com/gollum/gollum/issues/702) for how to implement basic auth middleware.
* I've recently implemented something similar in a Rails app [here](https://github.com/repotag/repotag/blob/master/app/classes/repotag_auth_proxy.rb#L64).

**Comment by dometto** [comment]
Also, the docs are mostly the public wiki for this repo. Please feel free to explain anything you run into there!

**Comment by Naatan** [comment]
Thanks @dometto. I figured gollum didnt support users/auth, but since it's fairly vital for public wiki's I expected at least a mention of it. Your answer perfectly addresses the question, I don't mind submitting it to the wiki but I'd feel like I'd be stealing your efforts as it'd just be a copy paste. Consider adding it or let me know if you're ok with my copy pasting it in there.

**Comment by dometto** [comment]
No worries, you're right we should mention this in the wiki. I'll try to type something up. But if you encounter anything else please feel free :)

**Comment by rgroux** [comment]
I use gollum with CAS auth, and i will make (ASAP) a doc/how to. I am actualy in a train in Milano. So i think i will commit on my page and hope for PR soon. 

This is a very basic auth. Just read/write, and no page modification, so everyone has edit button. 

/Richard

**Comment by dometto** [comment]
Please note that there is already a --no-edit command line switch (wiki_options[:allow_editing]). We're not looking to build authentication/authorization  support into gollum, as that can/should be done in a middleware. However, examples for such a middleware a very welcome (in contrib or the wiki).

**Comment by rgroux** [comment]
Indeed. I am titaly agréé with this. I use only standard gems. And if i talk about a PR it s only for docs or readme, notre à features.

In my opinion, it's only a nice must have for few peaple. 

May be i will write how to setup the cas server too for testing, because jassig is à bit complex and thé cas sever gem is simple

**Comment by dometto** [comment]
Sounds good @rgroux!

**Comment by rgroux** [comment]
Sorry, spellcheck on the phone sucks

**Comment by rgroux** [comment]
I create a new page  in the gollum wiki about CAS auth, it's done, sorry for the delay.

[Gollum with SSO](https://github.com/gollum/gollum/wiki/Gollum-via-Rack-and-CAS-SSO) with RO and RW access.

Hope it can help many users.

Enjoy
/Richard

**Comment by LeandroWaterfall** [comment]
Hi everyone!! good morning, i got a problem with gollum when i try to put a authentication (email/user), i don't know what i can do to fix that problem, i was read a lot documentation about, but don't work.. if someone can show me the light, im gratefull
