### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum#1050]
I'm looking to use gollum to document software, particularly to document Komodo IDE and Edit. One thing I'll need it to do is handle different versions of the software. For example when we release Komodo 10 the Komodo 9 documentation should still be available. Ideally there should be a way to easily switch to a previous "version" of a wiki page while viewing it.

That's my use-case, but it's by no means unique, which is why I'm coming here with it. It would be incredible if I could tag a commit and gollum could take this tag and say "hey, this page you're viewing was tagged with this name, wanna see it?", if that makes sense. My git-fu is not strong enough to know if that approach is feasibly, an issue I would foresee is that a tag covers a specific commit, and it might not be as easy as would be required for git to check what files were available at the time of that commit.

So I'm hoping to accomplish the following by posting here:

 * Is this a use-case that anyone is currently trying to address already
 * if no, would anyone be interested?
 * if no, I would be interested myself, but would appreciate your ideas on how to do this most effectively.

Thank you

**Comment by SkyCrawl** [comment]
Hello @Naatan 

your use-case definitely sounds amazing and personally, I'd love for Gollum to be able to satisfy it, however, I'm afraid it can not as of this moment, as you probably know. In a little more detail:

What Gollum can do for you now in regard to your use-case:
* Fully provide your documentation to the public, specifically one Komodo version only.
* Each page can be pulled in a past version, based on commits.

What Gollum can **not** do for your now in regard to your use-case:
* Pull each page in a past version, based on tags.
* Fully provide your documentation to the public, on all Komodo versions.

I'll be commenting deeply on the issue at hand below but for now, a small question:
Does something prevent you to do what you'd like to do in the usual way? Using (e.g.) MediaWiki to serve your pages, where each tagged version is effectively a folder on the HDD, all while having an "external" git repository to manage all the versions at once?

And to answer your questions:

> Is this a use-case that anyone is currently trying to address already?

I think not :(.

> If no, would anyone be interested?

I definitely would but note that personally, I'll be way too busy to work on this at least until October. And even then, I think it's a lot more important to first increase the level of Gollum's design and code :). While your use-case is definitely very very nice, I think it doesn't make too much sense to attempt to try to solve it before Gollum is ready for it and we solve much more pressing issues and problems.

> If no, I would be interested myself, but would appreciate your ideas on how to do this most effectively.

Then I suggest to read on :). Solving this use-case in Gollum requires a thorough revision of a part of its design, making the new design with all possible use-cases in mind and very probably also imposing several requirements on the underlying adapter technologies. Not a very easy issue at all :).

---

Use-cases and points to have in mind when solving the issue at-hand:

1. Pages in a Gollum repository are typically linked together and presently, they can not reference specific versions of one another. If they could, they should be able to reference both a tag and a commit (special syntax would have to be devised). Also, when a link doesn't reference a commit or tag, two different use-cases have to be handled (both of which can be what the user wants):
    * Following the link will keep the original page's version.
    * Following the link will **not** keep the original page's version and display the latest version.
    * And what if both of these use-cases are desirable within the same Wiki? Things are starting to get quite a bit complicated :).
2. URLs should definitely contain either the referenced commit or the referenced tag. Shouldn't be much a problem since presently, Gollum uses an HTTP parameter to reference commits. Things get more complicated, however, if some users wanted the tag to be displayed in the base path (e.g. `my-domain.smth:4567/docs/v9.0.0/...`, as it would most likely be with webservers serving static pages. It would also allow to directly load a specific tagged version of the Home page as Gollum returns the Home page for a request like `my-domain.smth:4567`. This would especially be required if Gollum eventually decides not to hardcode the Home page's name, as I personally think it should have done a long time ago. Be it as it may, putting the referenced tag into the base path requires that we find a reliable way to distinguish between `base-path` (`docs/v9.0.0/` in the example), tag reference (`v9.0.0` in the example) and the URL of a page (`...` in the example). Also, we would need to ensure that the tag reference is always present in the URL for a past tagged version of a page and always notice it when requests are made.
3. Gollum would probably have to find a nice way to include the commit/tag in the currently viewed page. And from there, users should be able to easily switch between tags.
4. The "all pages" view should probably support past repository versions, including tags, which means that an interface to switch between commits/tags has to be made.
5. **Most importantly**, underlying git adapters have to be able to work with tags. At the very very least, one of them.
6. As a bonus, we could consider adding a UI interface to tag the currently displayed version of a (e.g.) page.

**Comment by dometto** [comment]
I appreciate your use case, @Naatan, but I'm not sure git's (linear history) architecture is well suited for this (having parallel histories). For instance, what if you want to edit something in the docs of an older version? That's going to be a new commit, and hence a new tag will be necessary.

The more natural way to do this in git/gollum, I think, is just to have multiple directories (or even submodules) for each version's docs in the root of the repo. So I don't think we'll be adding this to our feature list.

**Comment by Naatan** [comment]
Hey guys. @SkyCrawl thank you for your thorough response - much appreciated!

Having been playing with this in my head for 2 days though I came to the same conclusion as @dometto, there exists the chance that one may want to edit something in a previous version. Additionally for my use-case I don't want to version all of the wiki, just certain sections (folders). Folders do indeed make more sense in that regard. I still think gollum (or a module for gollum) could handle a lot of this logic, but I'll see about implementing such logic first as I suspect my spec may change a few times before I finalize it.
