### ISSUE TITLE
Set page_file_dir for internal use only

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum#1052]
I want to set a sub directory for wiki pages, however it seems that when I use `page_file_dir` (or `--page-file-dir` for the CLI) it exposes this directory to end-users. Eg. if I set it to "wiki" then this path will be represented in the url.

I want to set a sub directory that is only internally used. From an end-user perspective the root directory should not change.

Any way of doing this?

**Comment by SkyCrawl** [comment]
Hello @Naatan 

I'm afraid you can not do anything about this at the moment, except forking both `gollum` and `gollum-lib` and fixing all the necessary code, which might prove unexpectedly difficult for certain reasons :(.

I may be wrong but it seems to me that it hasn't been done before either because noone noticed or because it spans both the above gems. I will add it to the list of known limitations, thanks for reporting :).

@dometto 
Let's label this issue?

**Comment by bartkamphorst** [comment]
> I want to set a sub directory for wiki pages

@Naatan Just so I'm clear on what you're asking, could you tell me a little more about your setup? Is it that you have an existing git repository and want to add wiki pages to that repo? Or is it that you don't want the pages being saved to gollum's root directory when you run `./bin/gollum`?

**Comment by Naatan** [comment]
Basically I have a repository that in its root has public, views and templates folders. These should not be picked up by gollum as being part of the wiki.

The only way around it that I've found is to have the wiki itself be a different repository, which I then run gollum on. This is not ideal however, I'd prefer to only have 1 repository that covers the project.

**Comment by dometto** [comment]
This has been implemented in `5.x`. See #1328

**Comment by dometto** [comment]
Oops, wrong issue. Reopening.

**Comment by dometto** [comment]
Implemented in 5.x!
