### ISSUE TITLE
Tag Based Organization

### ISSUE THREAD

**Issue by maxchill** [gollum/gollum#1058]
I love my Gollum wiki, however for large repositories the organization structure of a filesystem is very limited.  If an article applies to many topics it's difficult to decide where to put it.

Would be fancy if gollum supported tagging, perhaps in a way similar to jekyll blog post frontmatter, to organize pages.  A periodic indexing process would occur to generate navigation by tag.  Search would also support using the index.

For now the best we can do is just use the search feature.  Just thought I'd throw the idea out there and see if there is interest in pursuing this as a feature, or if alternatives are suggested.

**Comment by techwiz24** [comment]
I'm sure you've already considered this, but the way I do it for a large repository is use sub directories. For example, I have a directory for `Virtualization` and inside of that one for each of the virtualization products we use. Pages that are specific enough go in the sub directories, and more general pages go in the more general folders.

An indexing process would be nice (perhaps as part of a post-commit or post-pull hook?) but (and correct me if I'm wrong) I don't believe `gollum` was designed for use as a server application. I think it's supposed to be more of a "run and commit to your wiki on your local machine", so I'm not sure how well an indexing service would go, especially because there is no database, so you would either have to write the indexes to the file system (which would pollute the working directory for git commits and merges) or keep it in memory (which may not be feasible for large wiki's, depending on the complexity of indexes, and would add a lot of startup time to rebuild indexes on every launch).

Jekyll works because it is a static page generator. It literally unwraps indexes and includes them in the pages themselves. I don't think this approach applies to gollum because it pulls page content from git.

**Comment by SkyCrawl** [comment]
@maxchill 
Thank you for the idea :). Alas... I must agree with @techwiz24 . Even if it is possible to successfully implement something like that (which it might well be...), it's definitely not a priority, even in a long run :(.

The only way to come close to your suggestion that I can see is:
* Make the index yourself... as a page :). Write out all your tags and link each of them to respective search page.
* Then, you can tag each page with arbitrary tags using (e.g.) HTML commentary.

The advantage of this approach is that you can structure the tags in whatever way you want - tables, lists, categories... or everything combined.
The disadvantage is that you need to maintain this yourself, so it's important to make the structure well :).

**Comment by dometto** [comment]
I agree with @techwiz24. See also https://github.com/gollum/gollum/issues/1050.
