### ISSUE TITLE
where can I find the API documentation?

### ISSUE THREAD

**Issue by eduOS** [gollum/gollum#1068]
Hello, thanks very much for such an awesome app.

I'm intending to develop a mashup based on your awesome gollum, but cannot find the documentation.

What worse, it seems that there may exist only a Ruby version and no one for Python which I use now.

So, am I missing something?

Best regards,
Leo

**Comment by dometto** [comment]
I'm afraid I don't understand your question. This is a ruby project, not python. The api docs are easily findable, see the gollum-lib project's readme.

**Comment by bartkamphorst** [comment]
@eduOS You're right that [gollum-lib's API](https://github.com/gollum/gollum-lib/#api-documentation) is Ruby-based. Gollum does have a RESTful architecture however, as mentioned in [this issue here](https://github.com/gollum/gollum/issues/384). Gollum will return HTML and not something a little nicer like JSON, but you should be able to access the wiki pages via that route from any language, including Python. There are no explicit docs for this as far as I'm aware, so checkout [app.rb](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb) for available routes. Hope this helps!

**Comment by eduOS** [comment]
Thanks for your helpful reply. I may get it now. I'm trying to employ
Dulwich, a Git Python interface, now for the project.
