### ISSUE TITLE
Regression of #907

### ISSUE THREAD

**Issue by arianf** [gollum/gollum#1072]
I just install a brand new fresh version of Gollum. I am seeing a regression of #907. I am not able to see tables on a fresh install of gollem.

```bash
gollum --version
Gollum 4.0.1
```

<img width="980" alt="screen shot 2015-09-24 at 3 27 26 pm" src="https://cloud.githubusercontent.com/assets/7397857/10089559/098688a0-62da-11e5-9c28-c496e38e4e03.png">
<img width="765" alt="screen shot 2015-09-24 at 3 27 36 pm" src="https://cloud.githubusercontent.com/assets/7397857/10089558/098545a8-62da-11e5-9d53-9cfcdbdb48ea.png">

**Comment by arianf** [comment]
As pointed out by https://github.com/gollum/gollum/issues/907#issuecomment-142749177 

Red Carpet doesn't have Tables turned on by default!

**Comment by MAccadia** [comment]
Same Issue.
```
gollum --version
Gollum 4.0.1
```

**Comment by bartkamphorst** [comment]
@arianf @MAccadia Thanks for reporting. It seems to me though that the issue is with `github/markup` and how it chooses to render markdown through `redcarpet`. Or one might argue that `redcarpet`'s setting of not rendering tables by default is counterintuitive. Either way, the issue is not really with gollum, and I would suggest opening pull requests with either `github/markup` or `redcarpet`. The quickfix as proposed in #907 could also be helpful in the meantime.

**Comment by apfohl** [comment]
Hello, I have a freshly installed gollum 4.0.1 and there is no evidence of `redcarpet`. But kramdown is installed as dependency. I'm still not able to create tables. Did I miss the fix or some other issues about that?

**Comment by arianf** [comment]
@apfohl Try running `gem install github-markdown`, so gollum prefers `github markdown` over `redcarpet`.

**Comment by bartkamphorst** [comment]
Also, please check that you are running gollum using `bundle exec`.

**Comment by apfohl** [comment]
But Kramdown can create tables and it is installed as a dependency of gollum. Doesn't gollum know how to use Kramdown?

**Comment by apfohl** [comment]
@arianf It works if I install `github-markdown` btw.
