### ISSUE TITLE
MathML not rendered

### ISSUE THREAD

**Issue by amacraigne** [gollum/gollum#1079]
Hello,
I need to had math equations in markdown gollum pages.
I enabled mathjax with --mathjax.
It seems to work when equations in TeX format but no in MathML. In the following example, only the first equation is correctly rendered : 

```
 \\\(2^2\\\) 

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msup>
    <mn>2</mn>
    <mn>2</mn>
  </msup>
</math>
```

From what I've read with the default mathjax configuration file I'm allowed to put equation in mathml format in markown page ?

am I wrong ?

Regards !

**Comment by SkyCrawl** [comment]
> From what I've read with the default mathjax configuration file I'm allowed to put equation in mathml format in markown page. Am I wrong?

No, you're not - Gollum includes the latest MathJax into pages and MathML should be supported indeed. The problem here seems to be related to the sanitization process. For security reasons, Gollum will not render [HTML tags that it doesn't "know"](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/sanitization.rb) or that could be used for bad purposes. The solution is simple - add MathML tags into the linked sanitizer. This needs to be discussed with the project maintainers, however.

@dometto 
Any objections?

**Comment by bartkamphorst** [comment]
Given that we support mathjax, I think it makes sense to also allow mathML tags. So personally I would accept a PR in which all mathML tags are white-listed.

**Comment by dometto** [comment]
:+1:

**Comment by bartkamphorst** [comment]
@amacraigne Are interested in working on a PR for this?

**Comment by amacraigne** [comment]
In the file sanitization.rb:
I added in the ELEMENT array the following tags :
* math
* mrow
* mi
* mo
* mfrac
* msqrt
* msup
* mn
* mtext
* msubsup

and now my equation are rendered. I can find an exhaustive list of all math tag. But I think the full correction is to put all the tag in this list in the ELEMENTS array ?

**Comment by dometto** [comment]
That's right :-) If there is an overview page of all the mathjax tags it would be great to link to that in the wiki, in case something ever changes.

**Comment by bartkamphorst** [comment]
This [element reference](https://developer.mozilla.org/en-US/docs/Web/MathML/Element) should be helpful.

**Comment by dometto** [comment]
@amacraigne, do you need more info to implement the fix?

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum-lib/pull/267, which will be in the `5.0` release.
