### ISSUE TITLE
Include tag not working with macro

### ISSUE THREAD

**Issue by karas1999** [gollum/gollum#1104]
Hi.
When using an include tag with macro, it can not be recognized correctly while normal page link tag can. For example:

I made a custom macro `GetParentPageName()` to get the parent page name inside a Footer.
In the "Home" page footer, the `GetParentPageName()` will return "Home" correctly as expected. 
Then I use this inside a include tag and a normal page link tag:

```
1. [[test-<<GetParentPageName()>>]]
2. [[include: test-<<GetParentPageName()>>
```
The 1st sentence will link to `test-Home` correctly.
The 2nd sentence will cause a problem shows: 
```
Cannot include /test-Home - does not exist yet
```
But the /test-Home page is exist. Even when you click the /test-Home inside the second sentence, it will link to the page correctly. Only the include can not work. 

I think there must be some mistake in the "include" syntax. But I can't find where to change the "include" behavior in the source file. I hope someone would help me with this. Thank you.

**Comment by bartkamphorst** [comment]
Include tags are processed in the tags filter in gollum-lib. Have a look [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/tags.rb#L100-L115).

**Comment by dometto** [comment]
Indeed. So this is by design: anything between `[[ ]]` is extracted by gollum so that it's not parsed by the markup-rendering gems, macros, etc. What you want to accomplish will be quite difficult, but you could try this:

1. Change the order in which different filters are processed by [configuring a custom filter chain](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/wiki.rb#L250), making sure `:Tag` is before `:Macro`
  * Note: this may break other macros or tags!
1. Write a Macro that outputs the entire include tag you want. So something like `IncludeParentPage(prefix-)` which outputs `[[include: prefix-ParentPageName]]`

It's not easy but currently we're not aiming to support anything like this. If you need help in getting the above to work, you could try stackoverflow.

**Comment by karas1999** [comment]
@bartkamphorst , @dometto 
Thank you for your help. 
I spent several hours in reading the filter files, and finally realized that it is because of the filter_chain order. But making the `:Tags` before `:Macro` did not work. Seems that's because the `tags.extract(data)` will happen before `macro.extract(data)` and input the whole tag `"include: test-<<GetParentPageName()>>"` into the `@map` then when do `tags.process(data)`, it will use the data in the `@map` and got an http_error. 

Then I realized that maybe I can use the macro filter before every other filter. It's not needed to be added to the filter_chain. So I added some script into the render method of markup.rb file and it works as expected now: 
```ruby
    def render(no_follow = false, encoding = nil, include_levels = 10)
      @sanitize = no_follow ?
          @wiki.history_sanitizer :
          @wiki.sanitizer

      @encoding       = encoding
      @include_levels = include_levels

      data         = @data.dup
      filter_chain = @wiki.filter_chain.map do |r|
        Gollum::Filter.const_get(r).new(self)
      end

      # Since the last 'extract' action in our chain *should* be the markup
      # to HTML converter, we now have HTML which we can parse and yield, for
      # anyone who wants it
      if block_given?
        yield Nokogiri::HTML::DocumentFragment.parse(data)
      end
      # Use the Macro filter before every other filter.
      macro_filter = Gollum::Filter::Macro.new(self)
      data = macro_filter.extract(data)
      data = macro_filter.process(data)
      process_chain data, filter_chain
    end
```
