### ISSUE TITLE
Feature Request: Macros as part of wiki instead of server configuration

### ISSUE THREAD

**Issue by baszalmstra** [gollum/gollum#1109]
I would like to create macros as part of the wiki without having to change the server side of things. At this point I have to create a macro file, go to the server add it to the gollum configuration and restart the whole thing.

I would like to add a macro as a page on the wiki and be able to reference that. I don't care about the language. Ruby, javascript, lua, handlebars, anything will do. 

MediaWiki has a very nice plugin for this:
https://www.mediawiki.org/wiki/Extension:Scribunto

Realms.io does a very nice job as well:
http://realms.io/

**Comment by dometto** [comment]
Hi there,

Thanks for chipping in. Unfortunately, I don't think we'll be able to implement this properly. It would essentially require us to check any/all possible files which contain Macro definitions, then parse and load all the macros, *for each page request*. I also think restarting the server is not a terrible price to pay for the current Macro system.

(Possibly this functionality was more easy to implement in mediawiki because it uses a normal database as a backend.)

Of course, I'm happy to reopen this if others think it's an important feature to have.

**Comment by SkyCrawl** [comment]
@dometto 
> Unfortunately, I don't think we'll be able to implement this properly. It would essentially require us to check any/all possible files which contain Macro definitions ...

It can be implemented properly, e.g. using a specialized page inclusion. But a feature like that has many implications and I think that's the real problem. If anyone is interested, I could write a little bit more about that.

@baszalmstra
I can see and appreciate the purpose of your idea , but let me ask you: why don't you either configure SSH and sFTP access or SSH and git access on your server, and really restart the server manually (but remotely)? You could even make a script out of it :). Is your server sitting behind a strict firewall?

**Comment by abbeygamesci** [comment]
@SkyCrawl 
No obviously I could do it that way, but I'd like it to be something that I can do from the web without too much hassle.

**Comment by baszalmstra** [comment]
@SkyCrawl 
No obviously I could do it that way, but I'd like it to be something that I can do from the web without too much hassle.
