### ISSUE TITLE
How do I include a definition file when using rst?

### ISSUE THREAD

**Issue by chbrandt** [gollum/gollum#1144]
I edit my docs using restructuredtext. I would like to make use of some [docutils definition files](http://docutils.sourceforge.net/docs/ref/rst/definitions.html). In particular, I want to place some greek letters in one of my wiki pages.

I tried, for instance,
```
.. include:: isogrk1.txt

some text |egr| another text
```
but didn't work. I downloaded `isogrk1.txt` and placed it at the same directory as my wiki-page is.

If I copy-n-paste the `egr` definition,
```
.. |egr|  unicode:: U+003B5 .. GREEK SMALL LETTER EPSILON

some text |egr| another text
```
sure it works.

How can I accomplish what I'm trying to do(to `include` rst definition files)?
Cheers.

**Comment by dometto** [comment]
The short answer is: I don't know. :) Gollum just uses the `github-markup` for rendering markups. In order to find this out, you would have to delve into the details of how `github-markup` implements rst, for instance [here](https://github.com/github/markup/blob/master/lib/github/commands/rest2html). Or you could ask some of the folks there or on stackoverflow. Good luck!
