### ISSUE TITLE
--base-path "/" results in a redirect loop

### ISSUE THREAD

**Issue by whitty** [gollum/gollum#1149]
# Steps to reproduce
1. `gollum --port 80 --no-edit --config /path/to/config.rb --base-path /`
2. load http://localhost:80/
3. browser reports redirect error
4. Sinatra output

```
[2016-07-12 04:42:54] INFO  WEBrick 1.3.1
[2016-07-12 04:42:54] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2016-07-12 04:42:54] INFO  WEBrick::HTTPServer#start: pid=1 port=80
192.168.5.255 - - [12/Jul/2016:04:42:58 UTC] "GET / HTTP/1.1" 302 0
- -> /
192.168.5.255 - - [12/Jul/2016:04:42:58 UTC] "GET / HTTP/1.1" 302 0
- -> /
192.168.5.255 - - [12/Jul/2016:04:42:58 UTC] "GET / HTTP/1.1" 302 0
- -> /
192.168.5.255 - - [12/Jul/2016:04:42:58 UTC] "GET / HTTP/1.1" 302 0
- -> /
192.168.5.255 - - [12/Jul/2016:04:42:58 UTC] "GET / HTTP/1.1" 302 0
- -> /
... Snipped duplcates
```
## Alternatives
1. remove `--base-path /` works as expected mounted at `/`
2. replace  `--base-path /` with  `--base-path /somepath` works as expected mounted at `/somepath`
## Context

I'm trying to script deployment of gollum in a number of environments.  The gist of what I'm trying to achieve is:

```
gollum --port $port --no-edit --config $path_to_config --base-path $basepath
```

In my environment I default "$basepath" to "/" as described in the `--help` documentation.

**Comment by whitty** [comment]
I'm about 80% certain the issue will be here:

https://github.com/gollum/gollum/blob/master/bin/gollum#L74

**Comment by dometto** [comment]
Setting base path to `"/"` results in the redirect loop because of the way the `--base-path` option is implemented [here](https://github.com/gollum/gollum/blob/master/bin/gollum#L260). I propose to just remove the mistaken 'Default: /' language from the readme. @whitty: in your case I propose you just leave out the `--base-path` option unless it is set.

**Comment by whitty** [comment]
in that case could you just omit that base redirect if base_path is empty? 

```
          map '/' do
            run Proc.new { [302, { 'Location' => "/#{base_path}" }, []] }
         end if base_path.length > 0
```

**Comment by SkyCrawl** [comment]
@dometto is definitely right about the direct cause of the loop at [L260](https://github.com/gollum/gollum/blob/master/bin/gollum#L260). @whitty is definitely right about the hidden bug at [L260](https://github.com/gollum/gollum/blob/master/bin/gollum#L260), more likely at [L248](https://github.com/gollum/gollum/blob/master/bin/gollum#L248) though. Because of that, the code around [L74](https://github.com/gollum/gollum/blob/master/bin/gollum#L74) triggers a corner case bug. That particular code is incidentally my doing and the way I see it, L74 is perfectly fine but L90 is not. L90 should be:
```ruby
wiki_options[:base_path] = base_path unless base_path.empty?
```
since that's where the corner case bug really hits off. Even if the bug is not caught at L260, or L248, it is also not caught at L90, so both fixes are probably appropriate.

And hence, I don't personally think that `Default: '/'.` in the bin is wrong or that it should be removed.

Strange though, I've read that code so many times and as far as I can recall, it never occurred to me that there's a check missing.

**Comment by bartkamphorst** [comment]
Can confirm the issue (ruby 2.4.0).

**Comment by dometto** [comment]
Fixed in `5.x`
