### ISSUE TITLE
@wiki.pages not populated for subpages

### ISSUE THREAD

**Issue by PeteMichaud** [gollum/gollum#1150]
When I put `<<GlobalTOC()>>` into _Sidebar.md, it doesn't break, but doesn't actually populate because the `@wiki.pages` collections is empty when it's called from there. 

If I call it in Sidebar AND on a particular page body, then what I see is the TOC correctly rendered with links in the content area of the page, and the shell (like the title and div, with no pages listed) of the TOC on sidebar.

I imagine it has to do with when the Sidebar is loaded, but one thing I noted during debugging is that if I had it output to console for debugging, then the server would show the content rendering with the page collection, then AFTER that the sidebar rendering without the page collection. That means it's not just a load order thing, but in fact that `@wiki` is populated differently for the Sidebar somehow.

**Comment by dometto** [comment]
Thanks for letting us know. I'm guessing subpages don't populate (in the same manner as ordinary pages) due to performance issues. We'll have to investigate if we can fix this behavior without accruing any performance hits. One possibility is to change the `GlobalTOC` macro such that it attempts to populate when `@wiki.pages` is empty. PRs very welcome!

**Comment by dometto** [comment]
This has been fixed by https://github.com/gollum/gollum-lib/pull/283
