### ISSUE TITLE
Markdown does not render custom protocols

### ISSUE THREAD

**Issue by stevearm** [gollum/gollum#1160]
I'm using gollum for a local wiki, and I have some apps on my Mac supporting custom protocols. When I click on `<a href="bugtrac://issue/1234">bug</a>` in Safari it opens my local bug tracker app.

The markdown `[bug](bugtrac://issue/1234)` produces `<a>bug</a>` instead of `<a href="bugtrac://issue/1234">bug</a>`.

I don't know Ruby, so I'm not sure where to start looking. Is this rendering even done by gollum, or is there a markdown dependency somewhere that I should file the bug against?

**Comment by dometto** [comment]
The issue is caused because gollum works with a whitelist of protocols that are allowed in markup tags, for security reasons. However, you can simply add your `bugtrac` protocol to the whitelist by running gollum with a `config.rb` file (use the `--config path/to/config.rb` flag). This is explained [here](https://github.com/gollum/gollum/wiki/Security#customization).
