### ISSUE TITLE
Version bump on Rubygems

### ISSUE THREAD

**Issue by zachfeldman** [gollum/gollum#1194]
I'm on 4.0.1 and I realized the version hasn't been updated since like May of last year. I'm pretty sure recent contributions aren't included in the gem version including the ability to delete files :).

I can do a version bump PR if people are fans of this idea.

**Comment by dometto** [comment]
Yes, we should release a new verison. But https://github.com/gollum/gollum/commit/236680aab992d2e063fb3506494808cdd3c34005 introduces an API change, so arguably it should be a minor version bump. @bartkamphorst, any objections? If not I'll cut a new gem ASAP (since that would include some performance fixes, among other things.)

**Comment by bartkamphorst** [comment]
Agreed to the minor version bump.

**Comment by dometto** [comment]
Done!
