### ISSUE TITLE
Wiki Editor buttons are not Asciidoc aware

### ISSUE THREAD

**Issue by ellipticview** [gollum/gollum#1202]
When creating/editing an asciidoc page, the editor buttons insert markdown formatting.

**Comment by bartkamphorst** [comment]
This is not the case. When the page is asciidoc formatted, the buttons insert asciidoc syntax. My guess is that you actually had created a markdown page.

**Comment by ellipticview** [comment]
Maybe the cause of this issue is with my configuration. I'm using this config.rb to create an asciidoc-only Gollum:
```
# always include this:
Gollum::Page.send :remove_const, :FORMAT_NAMES if defined? Gollum::Page::FORMAT_NAMES

# ==== Limit supported formats to Asciidoc ====

# first remove all markups:
Gollum::Markup.formats.clear

# and then define the sole markup to be supported:
Gollum::Markup.formats[:adoc] = {
    :name => "AsciiDoc",
    :regexp => /adoc/
}
```

With this config I am seeing this behavior:
When first creating a document, the buttons insert markdown (e.g. the H1 button).
When pressing Edit on an existing document, there are no markup buttons at all.

**Comment by dometto** [comment]
Probably there is some minor difference in your definition of the asciidoc Markup, compared to the way gollum sets it up by default. Rather than first deleting all markups and then redefining asciidoc manually, try to conditionally delete all markups *except* asciidoc in your config. As the editor works with a default setup, I will close this for now, but feel free to let us know if you need more help.
