### ISSUE TITLE
Change default style in pygments 

### ISSUE THREAD

**Issue by dummys** [gollum/gollum#1216]
Hi,
Is it possible to change the default style color in pygments ?
List of styles is here: http://pygments.org/docs/styles/#builtin-styles
Thanks

**Comment by dometto** [comment]
Actually, I think gollum uses it's own style for highlighting. You could manually override [this](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/css/gollum.css#L574-L596) via the `--css` option.

However, since both `rouge` and `pygments.rb` provide their own CSS, it could be an option to use that in the future, and make the style configurable through `config.rb`. This is not a priority for us, but PRs are welcome.
