### ISSUE TITLE
Can't install gollum with gem

### ISSUE THREAD

**Issue by icymind** [gollum/gollum#1219]
env:
  - OS: alpine 3.4
  - ruby version: 2.4.1

When I run `gem install gollum`, I got an error:
```
ERROR:  Could not find a valid gem 'gollum-rjgit_adapter' (~> 0.3) in any repository
ERROR:  Possible alternatives: gollum-grit_adapter, gollum-rugged_adapter,blade-qunit_adapter, couch_rest_adapter, dm-redis-adapter
```

But the installation is successful with `gem install gollum -v 4.0.1`. Any advice?

**Comment by dometto** [comment]
This is because of a problem with `gollum-lib v4.2.4`, which accidentally depended on `jruby`. I just yanked the gem as you typed your comment (practically) and released `gollum-lib v4.2.5`, which installs successfully on my OS X machine. `gem install gollum` should also work again (or maybe it needs a second before becoming aware of the new version of `gollum-lib` on rubygems). Sorry for the confusion.
