### ISSUE TITLE
Using existing docs with Gollum

### ISSUE THREAD

**Issue by ranvijayj** [gollum/gollum#1286]
Hi, 

So I have an existing GIT repo of the following structure:

.
|-- code
|-- docs
|   |-- backend
|   |-- frontent
|   |   -- abc.md
|   -- qa
|       -- abc.md
-- models

So, docs are inside a folder docs. I cd into the repo and run `gollum`

But when I go to the web interface it opens `create home page page. I create it. Then go to `all` option near files. It only shows the newly created home page. 

In `wiki`, I could find nothing about serving existing .md files.

![screen shot 2018-01-17 at 4 23 13 pm](https://user-images.githubusercontent.com/10911504/35039061-c0dd2384-fba2-11e7-8018-be7107bd1137.png)

**Comment by ranvijayj** [comment]
@bartkamphorst Does this make more sense?

**Comment by bartkamphorst** [comment]
Where did `Home.md` end up? Try running `gollum` with the repo as an argument (so `gollum [reponame]`).

**Comment by dometto** [comment]
Possibly the rest of your files are on a different branch, not on `master`. In that case you need to tell gollum what branch to use.

**Comment by dometto** [comment]
I just actually ran into this confusion myself, by coincidence. It happens when you clone a repository that has a certain branch active: by default, the cloned repository will be on *that* branch, but `gollum` will use the (empty) `master` branch. So I'm 90% sure this is your issue. Either make sure to clone the repository in the right way (so that the `master` branch is actually cloned), or or use the `--ref` option to tell `gollum` to use a different branch.

In case this doesn't solve your issue, let us know and I'll reopen.
