### ISSUE TITLE
Markdown tables are not rendering properly in HTML

### ISSUE THREAD

**Issue by mravery** [gollum/gollum#1375]
I have read #907 and the discussion there didn't provide a solution to this issue. When I create a new page and paste the following into the editor, a table does not render:

This Markdown markup:

```
| Services      | Endpoints   |
|---------------|-------------|
| [[Google]]    | [[Blog]]    |
| [[Wordpress]] | [[Website]] |
|               |             |
```

produces this HTML output. **This is not rendered in HTML tables as expected.**

```
<div id="wiki-body" class="gollum-markdown-content">
    <div class="markdown-body">
      <p>| Services      | Endpoints   |
|---------------|-------------|
| <a class="internal absent" href="/Google">Google</a>    | <a class="internal absent" href="/Blog">Blog</a>    |
| <a class="internal absent" href="/Wordpress">Wordpress</a> | <a class="internal present" href="/Website">Website</a> |
|               |             |</p>

    </div>
  </div>
```
*Note that this table works on whatever version of `gollum` that Github is running on their servers.*

## Version

I understand that only issues related to 5.+ are being worked on. Unfortunately, I could not find a way to install the latest. The instructions on the README specify that using `gem` is the preferred method of installation and I am not familiar enough to know how to upgrade to a different version number nor even to figure out how to query the package manager for version numbers. **How do I upgrade my installation to 5.x?**

## Environment

```
macOS 10.13.6
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]
gem 3.0.1
gollum 4.1.4
```

**Comment by bartkamphorst** [comment]
> this table works on whatever version of gollum that Github is running on their servers.

Just FYI: Github does not use gollum anymore for their wikis. Gollum does still aim to be compatible with Github's wiki behavior though.

> How do I upgrade my installation to 5.x?

Since 5.x is a beta release, it should not yet be run in production. I recommend against upgrading at this point.

I can confirm though that your example table renders normally on the `5.x` branch.

Should you wish to try it out yourself, you can clone the project, checkout the `5.x` branch and run gollum with `bundle exec gollum`. If you need more help, it's best to ask around on StackOverflow.
