### ISSUE TITLE
Please fix the MathJax URL

### ISSUE THREAD

**Issue by bachmeil** [gollum/gollum#1390]
I understand that you will not be fixing bugs in the 4.x series. However, that is still the latest stable release that we are using. `--mathjax` functionality is broken due to the shutdown of the mathjax.org CDN.

It only takes a change in line 54 of lib/gollum/templates/layout.mustache to
`j.src = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML';`
and a change in line 61 in lib/gollum/templates/livepreview.mustache to the same thing to restore MathJax functionality.

**Comment by dometto** [comment]
@bachmeil sorry for the late reply, you can open a PR if you want and I'll do a bugfix release.

**Comment by jessebett** [comment]
Has this been fixed for 4.x yet? Currently gollum's mathjax does not display aligned equations correctly, it puts them all on a single line. I cannot determine why this is failing for `gollum --mathjax` but works on other mathjax formatted markdown servers (e.g. the [mathjax demo](https://www.mathjax.org/#demo).

When I look at the browser console I still get the CDN deprecation error for mathjax, indicating to me that this is not here.

Further, I can not test on 5.0 because I am unable to view existing wikis in the new verison. I just get create new pages for every existing page I am trying to test. So I am unsure if this is an existing issue in the 5.0 release.

**Comment by dometto** [comment]
This has not been fixed in 4.x. As it says in the issue template, we're not dedicating any resources to 4.x any more. As an exception I'd be happy to merge a PR and cut a new gem though.

Sorry to hear about your issues on 5.x! Please submit a more detailed bug report, including the output of `gollum --versions` and the relevant bits of your server log. However, please first read the 5.x release notes in the [wiki](https://github.com/gollum/gollum/wiki/5.0-release-notes). For example, behaviour concerning spaces in file names has changed in 5.x, which may lead to your issue.
