### ISSUE TITLE
5.x: Navigation() macro no longer displays subpaths

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1428]
Adding the `<<Navigation()>>` macro to a page lists all pages, just like the `<<GlobalTOC()>>` macro does. However, when adding arguments to the Navigation macro such as ``<<Navigation('My TOC', 'subpage', true>>` the rendered list is empty, even though the directory 'subpage' exists and contains pages.

**Comment by dometto** [comment]
Seems to me like that Macro could use a substantive refactor anyway

**Comment by dometto** [comment]
I think your problem was the use of quotes around the `subpage` argument. It works without. Nevertheless, I discovered that the Macro wasn't working correctly with page file dir and have a fix for it in https://github.com/gollum/gollum-lib/pull/348

**Comment by dometto** [comment]
Moreover, it looks like the following doesn't work:

* Directory `Sub` contains `Nested` with files
* within directory `Sub` a file containing
  * `Navigation(Bla, Nested)`

This is because the second argument to the Macro is interpreted as relative to the repo root, and not relative to the directory in which the file is located (in this case `Sub`).

Using `Navigation(Bla, Sub/Nested)` instead works.

Is this the desired behavior, or do we want to to interpret the second path as relative to the page's directory?

**Comment by bartkamphorst** [comment]
> I think your problem was the use of quotes around the subpage argument. It works without. 

Shouldn't it also work with quotes?

**Comment by bartkamphorst** [comment]
> Is this the desired behavior, or do we want to to interpret the second path as relative to the page's directory?

I'm fine with the current behavior.

**Comment by dometto** [comment]
Actually, the `Note()` macro also interprets single quotes as literal:

<img width="956" alt="Screenshot 2019-10-01 at 19 11 04" src="https://user-images.githubusercontent.com/147111/65984094-48827700-e47f-11e9-8be1-dd8a6cbb06cf.png">

Double quotes are respected for all Macros (including `Navigation()`).

**Comment by bartkamphorst** [comment]
> Double quotes are respected for all Macros (including Navigation()).

I see! Okay, that difference between single and double quoted strings is fine. Thanks for figuring this out.

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum-lib/pull/348
