### ISSUE TITLE
5.x Broken history and compare links for asciidoc files

### ISSUE THREAD

**Issue by fedegiova** [gollum/gollum#1441]
Gollum version:
Gollum 5.0.1b

With an asciidoc page the history links `http://wiki/Home.md/c4b30797a2bd78d6165bb1d08772e2e0b3321105` and compare links are broken because they refer to `<page>.md` (file extension is always .md) and not to `<page>.asciidoc`, if i manually change the URL to `.asciidoc` everything works as expected.

**Comment by dometto** [comment]
Can't reproduce this on commit `56e36df6bd67c5404ef0e41e6c4e00c2b843bc5d`:
```
$ bundle exec gollum --versions
Gollum 5.0.1b
Running on: x86_64-darwin17 with Ruby version 2.4.1
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.28.3.1
gollum-rugged_adapter 0.4.4
With the following renderers:
kramdown 2.1.0
```
Any differences with your setup?

**Comment by fedegiova** [comment]
Sorry, I mistyped the version command, here it the full one
```
Gollum 5.0.1b
Running on: x86_64-linux-gnu with Ruby version 2.5.1
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.28.3.1
gollum-rugged_adapter 0.4.4
With the following renderers:
asciidoctor 1.5.8
kramdown 2.1.0
```
I also have noticed that the problem appears only with files which had the extension changed during the history

![image](https://user-images.githubusercontent.com/15714045/68838540-15a6e200-06bf-11ea-8d20-b9e9aa41676e.png)

For example the Home file was `.md` at the beginning and then `.asciidoc` but all the links at left are rendered with `.md`

**Comment by dometto** [comment]
> For example the Home file was .md at the beginning and then .asciidoc but all the links at left are rendered with .md

Thanks, that must be the issue then!

**Comment by dometto** [comment]
There are two problems here:

* [This bug](https://github.com/gollum/rugged_adapter/issues/38), which is causing it to look for the `.md` instead of the `.asciidoc`. That's easily solvable.
* However, when that's resolved, there remains a further problem: the url we're linking is generated using the *current path* of the page.

Solving the latter is more difficult. It will require us to keep track of changes to the filename in each commit, and link to the correct filename for each revision.
