### ISSUE TITLE
'Untitled' Text Showing Up on All Pages in 5.x

### ISSUE THREAD

**Issue by TheCedarPrince** [gollum/gollum#1481]
# Problem: 

I have a string of text saying 'Untitled' popping up on every page of my Gollum Wiki and I have no idea why it is showing up. Here is what it looks like:

![image](https://user-images.githubusercontent.com/29561456/76710540-c5787480-66de-11ea-9de3-a8b9f1955c1f.png)

It's so peculiar because I have an empty markdown file called `test.md` and it is still showing up. Any thoughts as to why this text is showing up?

# Information to Reproduce:

This is currently affecting all my files - I do not remember it always being present though. I created an empty mkd file and then ran gollum using the following:

`bundle exec bin/gollum [Path-to-wiki] --emoji --h1-title --no-display-metadata`

# Gollum --versions:

Here is my `gollum --versions` output:

```
Gollum 5.0.1b
Running on: x86_64-linux with Ruby version 2.6.5
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.99.0
gollum-rugged_adapter 0.4.4
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```

# Conclusion

I have tried everything I can think of to get rid of this but to no avail. Any thoughts?

**Comment by dometto** [comment]
Very odd! I can't reproduce this.

You seem to be using the grit adapter rather than the rugged adapter. We're currently switching around the default dependencies for the various gollum gems, so that may be why. Try doing `git pull`, a `bundle install`, and then, if necessary, specifying `--adapter rugged` to explicitly use the rugged adapter. Let me know if that makes a difference.

**Comment by TheCedarPrince** [comment]
That fixed it! Not sure what the deal was but we are good to go now!

**Comment by TheCedarPrince** [comment]
That fixed it! Not sure what the deal was but we are good to go now!
