### ISSUE TITLE
MathJax migration from 4.x to 5.x

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1502]
I am heavily using MathJax on my wiki. I have a setup that renders LaTeX equations correctly with Gollum 4.1.4, but with 5.x branch LaTeX rendering is broken (shows as normal text). I suppose there is some migration that needs to be done - perhaps installing a gem or a software package in the system? Whatever that is it should be documented in the release notes.

**Comment by dometto** [comment]
@jstolarek what commit of 5.x are you on? It may be you just need to pull in the newest version, we recently fixed MathJax support in it. If you're already running the latest, please show us the output of the "Console" (in your browser's web development view)?

**Comment by jstolarek** [comment]
Indeed, I didn't notice there are new commits - sorry about that! However, I notice at least one change in semantics and I'm not sure whether this is a change in MathJax or a bug in Gollum. This snippet:

```
$\$ V \equiv \textbf{let } x = V \textbf{ in } \lceil x \rceil$
```
renders correctly on 4.x as:

![gollum1](https://user-images.githubusercontent.com/1597921/77688524-1cf8c900-6f98-11ea-8119-bfc82e1d407b.jpg)

But on 5.x it shows as text:
![gollum2](https://user-images.githubusercontent.com/1597921/77688605-487bb380-6f98-11ea-9c08-740671d1d0d0.jpg)

**Comment by jstolarek** [comment]
When I switch to rendering with `github-markdown` the problem goes away and everything renders on 5.x in the same way as on 4.x. It looks like this isn't a Gollum problem? Should this perhaps be reported upstream?

**Comment by dometto** [comment]
We definitely want MathJax to work with the default Kramdown renderer, as well. Is your example MathJax line inline math, or its own block? In the latter case, I know that in `5.x` at least you have to use:

```
$$ ... $$
```

(Instead of the single `$`)

**Comment by dometto** [comment]
Confirmed that:

1. this is an issue only with inline math, and not with display math
2. moreover, it only fails when using `$ $` syntax, not when using `\\( .. )\\` syntax for inline math

So it looks like kramdown might be substituting single `$` signs.

**Comment by dometto** [comment]
The problem is even more specific. This:

` $ a \rightarrow b $`

Renders fine inline. The problem is that your snippet has the `\$` symbol inside it, which is causing the tag to be closed immediately.

You can anyway use the alternative `\\( ... \\)` syntax for inline math. But if the `$ \$ $` does work with other renderers, I'll look into fixing it.

**Comment by dometto** [comment]
Actually I'm also seeing this behavior when:

* using e.g. the `CommonMarker` gem.
* on 4.x with `github-markup`

Apparently the markdown rendering gems replace the `\$` with `$`, and that's correct markdown rendering behavior. So I think this problem is just specific to `$ ... $` snippets with `\$` in them. I would advise just using the `\\( ... \\)` syntax in this case.

Feel free to reopen if you have another question!

**Comment by jstolarek** [comment]
Thanks. The `\\(...\\)` works as expected. I switched to `CommonMarker`, I'll see how that goes.
