### ISSUE TITLE
Feature request: Macro markdown links and changing warn octicon icons

### ISSUE THREAD

**Issue by DanSman** [gollum/gollum#1545]
Hi

I'm sorry to disturb you so much at the moment. :/

I'm trying to add a link to the note macro with html or markdown. Both aren't working. Are there plans to implement this?

I would also like to change the warn icon, which seems to me not possible right now. Any chance to implement that too, like with the note macro?

I have also another question about the editing mode. I disabled it and I can't compare versions without having the edit mode set on true. Is it possible to compare different versions without having the edit mode activated? Should I do another issue about it? I don't wanna bother you so much :)

Thanks
Dan

**Comment by dometto** [comment]
> I'm trying to add a link to the note macro with html or markdown. Both aren't working. Are there plans to implement this?

With markdown won't be possible, but HTML should work. For me it works with this syntax:

`<<Note(<a href='bla'>Test</a>)>>`

What are you trying?

> I would also like to change the warn icon, which seems to me not possible right now. Any chance to implement that too, like with the note macro?

The idea behind the `Warn` macro is that it uses one specific icon, because it performs one specific function (warning),  whereas for the `Note` macro, the idea is it could perform multiple features, so we allow the user to specify a different icon. If you want to change the specific icon the Warn macro uses, your best bet it is to subclass [this](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/macro/warn.rb) Macro class, or just create your own. You can include it using a `config.rb` (and the `--config` command line option).

> I have also another question about the editing mode. I disabled it and I can't compare versions without having the edit mode set on true. Is it possible to compare different versions without having the edit mode activated? Should I do another issue about it? I don't wanna bother you so much :)

I can confirm that a page's History is empty (and so compare doesn't work) when using `--no-edit`. Yes, please open a new issue for this!


.

**Comment by DanSman** [comment]
Hi

Thanks for reply.

Not sure what went wrong, I guess the double quotes were wrong. Anyhow, HTML in macro works. 

Thanks for the warn solution. That's perfect!

The history of my pages is not empty, but it redirects me to the error message that the edit function is disabled. When I try to compare the versions.
