### ISSUE TITLE
Video controls removed

### ISSUE THREAD

**Issue by svenssonaxel** [gollum/gollum#1587]
**Describe the bug**
The `controls` attribute of `video` elements is removed by sanitization

**To Reproduce**
1. Edit a .md file
2. Add a video tag, like `<video controls="controls" src="example.mp4" />`
3. Save and view the page.
4. A video is shown, without controls. Viewing source will reveal that the `controls` attribute is removed.

**Expected behavior**
A video is shown with controls.

**Environment Info**

```
Gollum 5.0.1
Running on: x86_64-linux with Ruby version 2.7.1
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: github/markdown
Other renderering gems:
org-ruby 0.9.12
wikicloth 0.8.3
```

**Potential Fix**

I have found that this issue can be fixed by adding the following:
```
::Loofah::HTML5::SafeList::ACCEPTABLE_ATTRIBUTES.add('controls')
::Loofah::HTML5::SafeList::ALLOWED_ATTRIBUTES.add('controls')
```
to the beginning of the file `/usr/local/bundle/gems/gollum-lib-*/lib/gollum-lib/sanitization.rb`

**Comment by dometto** [comment]
Thanks for the report. I do not know why `controls` is not by default included among safe attributes. The question is whether we want to override the whitelist by default. I would be ok with that if we can find out what the rationale behind Loofah's not whitelisting `controls` is, and find some proof that the attribute is actually safe. Otherwise, you can add the very fix you suggest in a `config.rb` file and thereby solve the issue locally.

**Comment by svenssonaxel** [comment]
> The question is whether we want to override the whitelist by default.

It seems this is already done. The first line in sanitization.rb is:
`::Loofah::HTML5::SafeList::ACCEPTABLE_PROTOCOLS.add('apt')`

> I would be ok with that if we can find out what the rationale behind Loofah's not whitelisting `controls` is, and find some proof that the attribute is actually safe.

Loofah [claims](https://github.com/flavorjones/loofah/blob/e14b903cafe5bd2beccf0b6fca80c94d338b632b/lib/loofah/html5/safelist.rb) to use HTML5lib's safelists, which I believe might refer to [this](https://github.com/html5lib/html5lib-python/blob/8df6cc90c7b12598ddb9e25eab64a6d1eb04d661/html5lib/filters/sanitizer.py), where `controls` is indeed included as a safe attribute. However, the entire file is marked as deprecated, with a reference to [bleach](https://github.com/mozilla/bleach), where the [sanitizer](https://github.com/mozilla/bleach/blob/master/bleach/sanitizer.py) is very restrictive and won't even allow `video` tags at all. I don't know why.

> Otherwise, you can add the very fix you suggest in a `config.rb` file and thereby solve the issue locally.

How? I tried adding the same code listed above, but unfortunately this does not seem to work.

**Comment by dometto** [comment]
I just noticed you can use the `<<Video(file.mp4)>>` Macro and it will generate a video with controls. There is currently no way for that Macro to *disable* controls -- but a parameter for that could be easily added if desired. I hope this solves your issue; if it does not (because you are unable/do not want to to use the macro for some reason), please feel free to reopen.
