### ISSUE TITLE
Ruby Sass has reached end-of-life and should no longer be used

### ISSUE THREAD

**Issue by JustCallMeCrash** [gollum/gollum#1616]
Just letting you know I'm getting this error when I install gollum gem
``` 
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

**Comment by dometto** [comment]
We are aware of this, but the main alternative (`sassc`) unfortunately does not play well with JRuby. So for now we have to just live with this deprecation warning. It's unfortunate that the maintainers of Ruby Sass hose to actually *depracate* their gem, rather than discontinue development, as it is perfectly functional, and doesn't really pose any security risks. Thanks for letting us know though!

**Comment by JustCallMeCrash** [comment]
Thanks for the reply and the thorough explanation.  Also, thanks so much
for this awesome tool - I love it.

**Comment by svoop** [comment]
@dometto I'll add my question to this old issue before opening a new one... possibly in vain:

There's a [similar case in gollum-lib (rugged vs rjgit)](https://github.com/gollum/gollum-lib/blob/master/gollum-lib.gemspec). Would the same be possible here, deprecated sass for JRuby and sassc otherwise?

**Comment by dometto** [comment]
@svoop I'm on the go so can't investigate thoroughly, but IIRC we switched to using `terser` on both JRuby and MRI a while ago. Let me know whether that adresses your concern. :)

**Comment by svoop** [comment]
@dometto Not sure about `terser`, but there is a commit 8deeea5349dcb971f8c386a1d0fb5edd61df4ecc on Master (21 Dec 2022) which switches to `sassc-embedded`. However, the current gollum-5.3.2 release quite a bit later in May 2023 appears not to have been made off Master but maybe the v5.3.2 branch which still depends on `sass`. In any case, a future release off Master will mark the end of `sass`, so I'll just wait. Thanks for the reply!
