### ISSUE TITLE
home.md is not recognized as Homepage

### ISSUE THREAD

**Issue by tholu** [gollum/gollum#1665]
I have cloned an existing Gitlab wiki with the homepage being in a file called `home.md` (lowercase h). After starting `gollum`, I am prompted to create a new page `Home.md`. Gollum is otherwise unusable.

**To Reproduce**
1. Clone an existing wiki with `home.md`
2. Start gollum
3. Go to http://localhost:4567/
4. Be prompted to create a new page "Home" instead of viewing the existing homepage

**Expected behavior**
Expected to view the existing wiki/homepage

**Screenshots**
![Bildschirmfoto 2021-02-03 um 13 42 03](https://user-images.githubusercontent.com/316763/106748513-a0a62c00-6625-11eb-89a0-bd5e8e72fcc6.png)

**Environment Info**

```
Gollum 5.1.2
Running on: arm64-darwin20 with Ruby version 3.0.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none
```

Running on macOS 11.2 Big Sur with apfs.

**Comment by dometto** [comment]
Yes, since version 5.0 [gollum file names are case sensitive](https://github.com/gollum/gollum/wiki/5.0-release-notes#filenames-are-now-case-sensitive). It looks like gitlab is either still using an older version of gollum, or has chosen to override the default filename. Two options:

* get gitlab to upgrade / change their default filenames
* we could build in some leniency and look for `"home.ext"` in case `"Home.ext"` is not found

The latter doesn't seem unreasonable per se, but it's important to realize that gollum is a project independent from gitlab. We don't want to have to maintain compatibility with every downstream user if they choose to modify gollum's default behavior.

**Comment by tholu** [comment]
@dometto Thanks for your fast response. I'll check if Gitlab also recognizes `Home.ext` and will try to rename the file as a quickfix. The leniency approach seems the most user-friendly in general.

**Comment by bartkamphorst** [comment]
I'm fairly certain that this behavior is determined in `gollum-lib` [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/wiki.rb#L141). So you might be able to resolve this locally by setting `@index_page` to `home` instead of `Home` in your `config.rb`. 👍

**Comment by dometto** [comment]
True @bartkamphorst! That seems like the way to go.

**Comment by dometto** [comment]
For anyone finding this issue, you can also run gollum with the `--lenient-tag-lookup` switch for compatibility with gollum 4.x based wikis (like gitlab's).
