### ISSUE TITLE
Gitlab compatibility: home.md and _sidebar.md are not recognized

### ISSUE THREAD

**Issue by griffin-warrior** [gollum/gollum#1684]
Hi,

I find that the first letter of names of the files `home.md` and `_sidebar.md` created by Gitlab (CE, version 13.8.3) are not capitalized by default. 
But, Gollum (version 5.1.2) only recognizes `Home.md` and `_Sidebar.md`, whereas Gitlab recognizes both of them.
Maybe Gollum should accept them the same way.
Just a personal recommendation.

Best Regards,
Wayne

**Comment by dometto** [comment]
Thanks for letting us know. This was reported before. The issue is that since `v5.0`, gollum's filenames are case sensitive. This is intentional, and makes for better performance (among other things, see [here](https://github.com/gollum/gollum/wiki/5.0-release-notes)). It looks like gitlab is still using version `4.x` of gollum. Perhaps you should request that gitlab upgrades to gollum-lib `5.x`. 

Alternatively, you could ask them to capitalize their default filenames so gitlab, github, and gollum wikis stay compatible.

For now, you can change the default homepage in gollum in your `config.rb` with the `:index_page` setting.

**Comment by griffin-warrior** [comment]
@dometto Thanks for your explanation. I think the better solution is to capitalize them manually in Gitlab.
