### ISSUE TITLE
Feature Request: Serve different git repos with different configs

### ISSUE THREAD

**Issue by arnold-maderthaner** [gollum/gollum#1727]
It would be great if there is an option to serve different git repositories (which contain markdown files) with different configurations inside 1 gollum instance. F.e. having 1 git repo which is RW and another git repo which is RO (with --no-edit option). Is that possible already ?

**Comment by dometto** [comment]
The way to go for this would be to simply run different gollum instances for the different repos. Since gollum is a `rack` (sinatra) app, you can simply "mount" different wikis at different endpoints. Here's an illustration of this approach using Rails (but you could use a different rack-compatible framework): https://stackoverflow.com/questions/13053704/how-to-properly-mount-githubs-gollum-wiki-inside-a-rails-app
