### ISSUE TITLE
Add ability to set  host and port options in config.rb

### ISSUE THREAD

**Issue by harleypig** [gollum/gollum#1738]
Please add the ability to set the host and port options in a config.rb file.

This would make it possible to create a single `gollum@.service` file that can be used for multiple wikis.

**Comment by harleypig** [comment]
I tried doing the following in my config.rb, but it didn't seem to work. What's the difference between `wiki_options` and `options` in `bin/gollum`?

    options = {
      :port => 6000,
      :bind => '0.0.0.0',
    }

    Precious::App.set(:options, options)

**Comment by dometto** [comment]
Those options are direct arguments to `Sinatra`'s `#run` method (or to `Rack::Server#new` in case you want to set a `base_path`), see https://github.com/gollum/gollum/blob/master/bin/gollum#L286

So calling `Precious::App.set(:options, options)` has absolutely no effect.

I'm not sure what you want to achieve. You can set a default port or host via the `--port` and `--bind` options on the command line, if you use `bin/gollum`. Or you can run gollum as a Rack service https://github.com/gollum/gollum/wiki/Gollum-via-Rack via a `config.ru`, which allows you to pass your own options to `Precious::App.run!`, and allows you to set all `wiki_options`. You just can't combine the two approaches.

If the problem is that you need a "neutral" exec script that fires up differently configured gollum instances, I would advise just writing your own shell script. I think it would only have to call `rackup` with the various `config.ru` files for each of your wikis as arguments.

**Comment by harleypig** [comment]
I'm trying to fit gollum into my current setup, which doesn't include a rack server at the moment.

I just want to stuff all the options into a config.rb file and start `bin/gollum --config /path/to/config` from a systemd service file where the config file path is built from the service file name. And I want a single `gollum@.service` file for any number of wikis where all I have to do is `systemctl --user enable gollum@somewiki`. Currently I'm creating an override file for the port.

**Comment by dometto** [comment]
You can get the exact same result by just running `rackup /path/to/config.ru` (from your service file, or from a wrapper script). You can have a separate `config.ru` for each wiki, with your `wiki_options` in it and specifying the host and port as arguments to `Precious::App#run`. So unless I'm missing something I see no reason to change the current functionality.

**Comment by harleypig** [comment]
I am the one who is missing something. I didn't know about rackup. I'll experiment with that.  Thank you.
