### ISSUE TITLE
Note and Warn macros showing plain HTML

### ISSUE THREAD

**Issue by DanSman** [gollum/gollum#1746]
Hi

Were there any changes for note & warn macros and html? Since one of the last updates, all note and warn macros display html code.

**Comment by benjaminwil** [comment]
I can't reproduce your issue using the latest Gollum code on `master`:

<img width="703" alt="Screen Shot 2021-07-25 at 3 36 43 PM" src="https://user-images.githubusercontent.com/883581/126915554-3ab78537-d9d5-4dba-bf4b-84f188f38162.png">

If you can provide more information about what you're seeing and what you expect to be seeing, I can investigate further.

**Comment by DanSman** [comment]
Hi

Perhaps it is not clearly explained how I meant it, sorry.
See the HTML code in the macro note:
![html_code_not_working](https://user-images.githubusercontent.com/28892085/126938167-5ec52d0d-4b66-45c6-82ff-9e335fa8c3e8.png)

```
<<Note("Audit framework compatibility with containers was fixed in Linux 3.15, see [<a href='https://bugzilla.redhat.com/show_bug.cgi?id=893751'>1</a>],<br>however interpreting audit records may be difficult as support for namespace ID is still work in progress, see [<a href='https://github.com/linux-audit/audit-kernel/issues/32'>2</a>].")>>  
```
It worked before.

**Comment by dometto** [comment]
Thanks for the clarification. This is caused by a recent security fix: https://github.com/gollum/gollum-lib/commit/5801cb3a99951c23120531fd556630de646aab75

Specifically [this line](https://github.com/gollum/gollum-lib/commit/5801cb3a99951c23120531fd556630de646aab75#diff-878b56d2dbdc64a7685cb79ba7a41a57bf7e50df763b212336edb999c82dcbbeR15)

So the question is:

* do we want to allow HTML in notes? I think there is a clear use case for it.
* can we do without the `CGI.escape_html` call, given that we are currently also sanitizing the content of the page after rendering Macro's? @yy0931, could you perhaps chip in on this?

**Comment by yy0931** [comment]
Yes, you can. I will make a PR which removes the escape_html.

**Comment by DanSman** [comment]
Thanks!
