### ISSUE TITLE
Gollum MathJax handles double backslash inconsistently

### ISSUE THREAD

**Issue by fanhongtao** [gollum/gollum#1765]
**Describe the bug**

Two questions come with the test page.

```md
$a \\ b$

\(a \\ b\)

$$a \\ b$$

\[a \\ b\]


| title |
|:--|
| a (b or c) |
```

1.  Same code get different results: 
    * Three of them (`$a \\ b$` , `\(a \\ b\)`, `\[a \\ b\]`) get result: `a b`  -- (A)
    * One of them (`$$a \\ b$$`) gets result `a <br/> b`  -- (B)
    * It's better to get result (B) for ALL four codes.
2.  In the table, expect value is `a (b or c)` , but gets `a borc` . Looks like Gollum treats `(b or c)` as a MathJax expression.

**Environment Info**

```
Gollum 5.2.2
Running on: x86_64-linux-musl with Ruby version 2.7.2
Using:
rugged 1.1.0
gollum-rugged_adapter 1.1
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
none
```

with `mathjax.config.js` :

```js
window.MathJax = {
  tex2jax: {
    inlineMath: [['$', '$'], ['\(', '\)']],
    displayMath: [['$$', '$$'], ['\[', '\]']],
    processEscapes: true
  },
  TeX: {extensions: ['autoload-all.js']}
};
````

**Comment by dometto** [comment]
The issue turns out to be that kramdown interprets a double backslash as a single escaped backslash, except when it is inside a `$$ block $$`. Unfortunately, the double-dollar blocks are the only ones that kramdown recognises as valid math. So I'm not sure this is fixable. We could allow only `$$ $$` style for displayMath by default, but this may needlessly break the `\(` syntax for page formats other than markdown. Perhaps the best option is just to clearly document this issue and encourage people to use `$$`?

**Comment by dometto** [comment]
> In the table, expect value is a (b or c) , but gets a borc . Looks like Gollum treats (b or c) as a MathJax expression.

Note that the backslash is an escape character in JavaScript. So since in your `mathjax.config.js`, you are using single backslashes, MathJax is in effect treating bare parentheses as a math delimiter. You need to use e.g. `'\\(' to set the delimiter to `\(`.

Annoyingly, due to the issue with markdown rendering described above, to get a single backslash in the HTML you need to write two backslashes in the gollum editor.

So with this config (the gollum default):

```javascript
  window.MathJax = {
      tex2jax: {
        inlineMath:  [ ['$','$'], ['\\(','\\)'] ],
        displayMath: [ ['$$','$$'], ['\\[','\\]'] ],
        processEscapes: true
      },
...
```

You need to use the following syntax for markdown:

```
\\( a b\\)
```

**Comment by dometto** [comment]
I  have updated the wiki with an explanation of this issue, and the recommendation to use the `$` and `$$` syntax. I'll close this for now. If more issues crop up or someone sees a better way of handling this, please feel free to reopen.
