### ISSUE TITLE
Change of default branch name from GitLab v14.0 (`master` to `main`)

### ISSUE THREAD

**Issue by ntmlod** [gollum/gollum#1813]
**Describe the bug**
Not at my best, it took me a while to realize why gollum did not find `Home.md` from barely initialized wiki repo.

**To Reproduce**
GitLab instance (v14.0 onwards) with new default branch name `main` not modified, create a new wiki from web interface and switch to the terminal for global editing with cloned local repo

**Expected behavior**
More of a flaw than an bug, one could expect that gollum handle together the previous and the new default branch name for GitLab (https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name).

**Comment by benjaminwil** [comment]
Thanks for reporting. I have a feeling that there are a few issues with regard to `master` no longer being the default branch name for some git forges, and Git itself more explicitly promoting alternative default branch names.

I think that some of these issues can be resolved by refactoring `gollum-lib` to have a more robust `Gollum::Wiki.default_ref` method. [Link to source][1].

[1]: https://github.com/gollum/gollum-lib/blob/v5.1.3/lib/gollum-lib/wiki.rb#L22-L24

**Comment by dometto** [comment]
@benjaminwil you're thinking we could check for the existence of `master` or `main` in the reflist there? That would be the most backward compatible. But just changing the default name to `main` could also be fine, since it looks like that's very much the new default.

For our own repositories, renaming looks like it should be very simple: https://github.com/github/renaming

The most annoyance I can see resulting is having to rename the branch and defaults in our local clones. Would it be ok if I went ahead and just made this change or do you think that might disrupt your workflow somehow, @benjaminwil  @bartkamphorst?

**Comment by benjaminwil** [comment]
I think that looking for “main” or “master” would be the safest way forward. 

But I think making the main branch name configurable would be the best option in the long term. I know of some repositories that opted to use “trunk” once “master” began to be deprecated, for example.

**Comment by dometto** [comment]
>  I know of some repositories that opted to use “trunk” once “master” began to be deprecated, for example.

That's good to know. It shouldn't be too hard to make this configurable across adapters --I can take of this!

**Comment by chbrandt** [comment]
Maybe I don't fully understand the actual issue and possible solutions being discussed here, @benjaminwil and @dometto , but I'll give my 2 cents anyway, may be of some value. 

I arrived here after I got `failed to create commit: current tip is not the first parent` when trying to upload (`--allow-upload` on) a file and I noticed there was a new `master` branch in my repo. It surprised me because I thought Gollum would simply use the current branch (which would have been `main`, but could as well be `bla`, or `gh-pages` for the matter).

1. If there is already a (.git) repository, Gollum should just use the current branch, unless an option ("--branch") is specified.
2. If in doubt, a query to remote (assuming `origin` is it) should help figure out the default HEAD:
    > ```bash
    > $ git remote show origin | grep HEAD
    >   HEAD branch: main
    > ```

**Comment by dometto** [comment]
Thanks for pitching in @chbrandt. We could consider using the current `HEAD` as a default for non-bare repositories, although I worry there are edge cases there (like when the repo is in [detached HEAD mode](https://www.cloudbees.com/blog/git-detached-head). However, all this assumes the repository has a working directory at all, i.e. is non-bare. Gollum also works, and should work, with non-bare repositories. So we still need to consider how to implement a sensible default for that.

**Comment by dometto** [comment]
See https://github.com/gollum/gollum-lib/pull/424 for a draft of how we could resolve this issue.

**Comment by mcknly** [comment]
Any update on this potential feature? Eager to be able to use gollum with my default Gitlab 'main' branch

**Comment by dometto** [comment]
All that's needed is a new gem release of some of the gems that gollum depends on. This isn't much work, but I've been a bit swamped lately. I'm aiming to cut the new releases over the weekend, but it maybe a couple of days later!

**Comment by bartkamphorst** [comment]
Should be fixed with the release of gollum-lib v.6.0. Thanks @dometto !

**Comment by dometto** [comment]
Yes -- that is to say, it's fixed when using `gollum` from the GitHub `master` branch, or the latest Docker image. For other users, please have a bit more patience until the new `gem` release of gollum 6.0 :)
