### ISSUE TITLE
Render README.md if available

### ISSUE THREAD

**Issue by challapradyumna** [gollum/gollum#1842]
Similar to github , render README.md on the directory page if available

**Comment by dometto** [comment]
I am not sure what you mean with "directory page" -- perhaps the Overview page? I am not very keen on the idea of rendering README under there: I think it would make the page quite crowded, but also README doesn't really have any special meaning in gollum (unlike say the Home page). This is partially because many people keep their wiki/docs outside of the repository root, or in a different repository altogether. Let me know if I've misunderstood though!

**Comment by challapradyumna** [comment]
We have a repo just for documentation and each directory / sub-directory has a readme which talks about the contents of the directory and directs people to what they are looking for. 

Directory Structure example
Root
- Readme
- Dir-1
  - Readme
  - Dir-2

**Comment by dometto** [comment]
Thanks for the further explanation. And where/when do you think each Readme should be displayed?

**Comment by challapradyumna** [comment]
If there is a readme file in a directory it should be rendered below the files section

**Comment by cmuc24** [comment]
Hi, 
at the moment, only top-level / root directory is rendering the README.md. 
Sub-directories not. 

#### Please add support for Sub-directories, like github.

README.md files are Markdown files that describe a directory. GitHub renders it when you browse the directory.
For example, the file /README.md is rendered when you view the contents of the containing directory: 
**EXAMPLE**: [https://google.github.io/styleguide/docguide/READMEs.html](https://google.github.io/styleguide/docguide/READMEs.html)
