### ISSUE TITLE
Feedback from a user

### ISSUE THREAD

**Issue by OneManMonkeySquad** [gollum/gollum#1892]
Hey,

I just started using Gollum a few days ago. Combining free, indestructible and always available github with journaling seems like a great idea. My first idea was to run a local Mediawiki which saves entries as text files but this seemed better.
edit: Forgot to mention. My goal was permanent, private information bucket. Like a notebook but for the 21. century.

Now, there are a few things I don't like. Running the thing on JRuby on Windows works but I'm not a fan. One thread is always running at 100% which seems absurd with what should be an easy 100% event driven software. I don't know if this is on the Java runtime but as a consequence my work laptop fans are running at 100% the whole time. Having to install either Java or running Ruby via WSL is not a great thing either.
Second thing is automatic pushing. I don't know if my use case is unusual but I have a local mirror of my repo which I push back to origin after I'm done editing. It seems to me like this would be a common thing and if the git repo gollum is running from has an origin I'd add a push/save button to the local site.
Next thing that comes to mind is a dark mode. I find a dark mode css online but it was outdated and I had to add a few things (still not perfect).
edit: Forgot something. Having the thing running as a hidden task bar app instead of a console window. Easy to run as a service on Unix, Windows not so much.

The problems outlined above make me want to rewrite the whole thing in go. Maybe I have the wrong expectations, missed something, JRuby is broken, I don't know. Let's talk.

**Comment by dometto** [comment]
> Now, there are a few things I don't like. Running the thing on JRuby on Windows works but I'm not a fan. One thread is always running at 100% which seems absurd with what should be an easy 100% event driven software. I don't know if this is on the Java runtime but as a consequence my work laptop fans are running at 100% the whole time.

That's not great, and might well be a bug. Would you mind filing a proper bug report for this, also comparing whether the same issue occurs with other Jruby apps or code, to identify whether this is an issue with gollum, JRuby, or the runtime?

> Second thing is automatic pushing.

https://github.com/gollum/gollum/wiki/Hooks#synchronizing-with-remote-repo

>  Next thing that comes to mind is a dark mode. I find a dark mode css online but it was outdated and I had to add a few things (still not perfect).

We have been waiting for Github Primer and have traced this in a general issue about improvements to the CSS.  Primer now has support for dark mode and a userr has started adapting it: https://github.com/gollum/gollum/issues/1394#issuecomment-991875073

Feel free open a separate issue requesting dark mode support and contribute with a PR. Gollum is entirely volunteer run and we try to do the best we can in our spare time.

>  The problems outlined above make me want to rewrite the whole thing in go. Maybe I have the wrong expectations, missed something, JRuby is broken, I don't know.

We can't decide how to use your time and we can't make every user happy, but if the JRuby issue is solvable, I'd encourage you to pitch in and help create support for dark mode -- seems to me like that would be significantly less work. In general though, I would like to point out that people use gollum in many different ways, and running it locally on Windows is only one use case (although one we would like to support as well as reasonably possible).

I'm going to close this as this contains multiple different points. If you have more concrete suggestions for improvement (like e.g. the dark mode issue) feel free to open separate issues. We're also happen to talk about possible future design decisions (but not, I think, the prospects of reimplementing something gollum-like in a different language) in a separate Discussion.

**Comment by OneManMonkeySquad** [comment]
@dometto that would be nice. I have not installed gollum on my private pc because Java is a big no-no.

Hooks: please don't hate me but I don't know how to use this. putting put in .git/hooks did not work and neither into config.rb. Do I have to compile gollum myself for this?

Darkmode: will do, thank you.

**Comment by dometto** [comment]
> @dometto that would be nice. I have not installed gollum on my private pc because Java is a big no-no.

Well, bundling the app into a JAR would still require the Java Runtime, of course, but I assume this is standardly available on Windows.

> Hooks: please don't hate me but I don't know how to use this. putting put in .git/hooks did not work and neither into config.rb. Do I have to compile gollum myself for this?

Yes, the documentation was rather brief. I've expanded the wiki page I linked to, I hope it's clearer now?

Please also open up an issue about JRuby performance on Windows if that bug is still occurring! We don't have regular access to a Windows machine so any help testing performance there is very helpful.

**Comment by aka13-404** [comment]
> It just occurred to me that if it would be a nicer user experience on Windows to not have to install JRuby, it's possible to use [warbler](https://github.com/jruby/warbler) to generate a self-contained, double-clickable Java Jar. @OneManMonkeySquad do you think that would be helpful to Windows users? We could consider auto-generating a jar like that when we push new releases. Of course, the performance issue on Windows would need to be solved for that.

I would appreciate it. I maintain a medium-sized-wiki for a github project, and I would like to use Gollum, but for now, I do not, since it's just too much of a hassle. Right now I use a second repo, to test my changes, and see if they work, and then just copy-paste everything on top of the "real" wiki, overwriting files.

**Comment by dometto** [comment]
@aka13-404 as a test I've uploaded a simple java `.war` file to the release assets for the last release: https://github.com/gollum/gollum/releases/download/v5.3.0/gollum.war

(NB: this is based on the last gem release, which is already a bit old, so it doesn't contain bugfixes/new features/performance enhancements from `master`. That'll have to wait until the new gem release, hopefully within a month from now.)

You should be able to run it with e.g.: `java -jar gollum.war -S gollum /tmp/lotr --mathjax` (replace `/tmp/lotr` with the path to your repository, and `--mathjax` with the config options you want).

Please let me know if that works as expected, and whether you see value in auto generating such a `.war` for every release. We could use a github action like [this one](https://github.com/marketplace/actions/upload-release-asset) to do that. (Any help with setting this up is appreciated.)

**Comment by dometto** [comment]
Simple command to generate the `.war`, using JRuby: `bundle install && warble runnable war`.

**Comment by aka13-404** [comment]
> @aka13-404 as a test I've uploaded a simple java `.war` file to the release assets for the last release: https://github.com/gollum/gollum/releases/download/v5.3.0/gollum.war
> 
> (NB: this is based on the last gem release, which is already a bit old, so it doesn't contain bugfixes/new features/performance enhancements from `master`. That'll have to wait until the new gem release, hopefully within a month from now.)
> 
> You should be able to run it with e.g.: `java -jar gollum.war -S gollum /tmp/lotr --mathjax` (replace `/tmp/lotr` with the path to your repository, and `--mathjax` with the config options you want).
> 
> Please let me know if that works as expected, and whether you see value in auto generating such a `.war` for every release. We could use a github action like [this one](https://github.com/marketplace/actions/upload-release-asset) to do that. (Any help with setting this up is appreciated.)

Brilliant, this is working nicely. Almost exactly what I needed. I would like to add the gollum.war to path variables, but something is missing.

I made a cmd with the following contents (with the idea of keeping it in the same repo where the wiki is, so that I can easily set it up on any machine where I have gollum and github access:
`java -jar gollum.war -S gollum %~dp0 --mathjax`

But I can't get it to read gollum.war from the PATH or similar. Any suggestions?

**Comment by dometto** [comment]
> I can't get it to read gollum.war from the PATH or similar. Any suggestions?

I think that's because your shell will only try to match the first word to what's in your `PATH`. As a workaround you could:

1. Create script `gollum.sh`*
2. Put `gollum.sh` somewhere in your path and make it executable
3. Run `gollum.sh /path/to/your/repo --with-your-options` 

Contents for `gollum.sh`:

```sh
#!/bin/bash
java -jar gollum.war -S gollum "$@" 
```

NB: this is how this would work with a bash script on *nix, I don't know if anything would be relatively different on Windows. But the general idea is to wrap the Java call in a script that you place in your `PATH`.

**Comment by dometto** [comment]
If you get an approach like that to work, @aka13-404, you could open a PR to add it our `contrib` directory.

**Comment by aka13-404** [comment]
Yeah, turns out I simply forgot how cmd variables work :)
I now have a "run_local_wiki.cmd" in the root directory of the wiki, with the following contents:
`java -jar %GOLLUM_WAR% -S gollum %~dp0 --mathjax`

And I have a path variable called `GOLLUM_WAR`, which consists of `Disk:\MyFolder\gollum.war`

This works very nicely, when I want to work on the wiki, I simply run the cmd, do all my stuff, and close it afterwards. 
I will have to familiarize myself with the possible options, but in general this seems like a solid method to me.

**Comment by dometto** [comment]
Update: from the next release on, `.war` files will be generated automatically. The Readme will document how to run gollum in that way. This means Windows users no longer have to install JRuby. The [latest release](https://github.com/gollum/gollum/releases) also contains a packaged `.war `.
