### ISSUE TITLE
Permission error when hosting with official Docker image

### ISSUE THREAD

**Issue by ColdTeapot273K** [gollum/gollum#2075]
**Please read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If your have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**
Gollum not functioning when deployed with Docker according to official manual.

**To Reproduce**
1. Go to [Docker guide](https://github.com/gollum/gollum/wiki/Gollum-via-Docker/b2bb2aa0343bd3e87a6a38352346c0402226b3a3#running)
2. Reproduce instruction steps.
4. See error in browser:
```
Rugged::ConfigError at /
repository path '/wiki/' is not owned by current user
```

**Expected behavior**
Starting page.

For comparison, [this](https://github.com/winkapp/docker-gollum) community setup works. But it's not maintained and not updated.

**P.S.**
Docker Compose manual from [here](https://github.com/gollum/gollum/wiki/Gollum-via-docker-compose) doesn't work either, with different kind of error about permissions when trying to save a document. Could you test it too please?

**Environment Info**
OS: Ubuntu 22.04.3 LTS x86_64
Docker version 25.0.1, build 29cf629

**Comment by marriotb** [comment]
I suspect that your first error ("Rugged::ConfigError") is related to the GitHub issue that's mentioned in the Docker Compose guide that you reference (step 4 in[ the instructions](https://github.com/gollum/gollum/wiki/Gollum-via-docker-compose#instructions)). Try adding the `safe.directory` value to your git config.

I, too, get the permissions error that you mention when following the Docker Compose guide. (Ubuntu 24.04.1 LTS on x86_64; Docker version 27.3.1; Docker Compose version v2.29.7)  If I find a workaround, I'll post it here, otherwise I'll raise a separate issue. 

Note that issue registers such as this should only reference one problem -- if there are two separate issues that have similar circumstances, raise them separately and cross-reference them. This ensures that each is addressed.

Regards
Brian

**Comment by dometto** [comment]
Actually, if you're using the latest version of the `gollumwiki/gollum` image, the fix with `safe.directory` should not be required, as this is already being added in the [Dockerfile](https://github.com/gollum/gollum/blob/master/Dockerfile#L49). If you were running into trouble here, @ColdTeapot273K, I suspect you were accidentally using an older version of the Docker image?

The docker compose instructions in the wiki were pretty complicated and outdated. I've simplified: https://github.com/gollum/gollum/wiki/Gollum-via-docker-compose -- if you're still running into trouble @ColdTeapot273K, please try again with those instructions and reopen this issue if it still doesn't work.

Regarding the second error identified by @marriotb, we've recently clarified the documentation and the docker image's error output: https://github.com/gollum/gollum/wiki/Gollum-via-Docker#adjust-permissions-to-mapped-host-volume
