### ISSUE TITLE
Is Gollum supposed to work on Windows?

### ISSUE THREAD

**Issue by tknerr** [gollum/gollum#23]
I'm trying to get gollum to work on a windows machine.

Environment:
- ruby 1.9.2.p0 (via rubyinstaller)
- msysgit: Git-1.7.0.2-preview20100309
- Windows XP / 32 Bit

After doing a `gem install gollum` (succeeds without errors) I am trying to run `gollum`, but get the following error:

```
   D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:753:in `read': Invalid argument - <internal:lib/rubygems/custom_require> (Errno::EINVAL)
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:753:in `inline_templates='
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:706:in `set'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:715:in `block in enable'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:715:in `each'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:715:in `enable'
    from (__DELEGATE__):2:in `enable'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra.rb:7:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/lib/gollum/frontend/app.rb:1:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/bin/gollum:90:in `<top (required)>'
    from D:/Ruby192/bin/gollum:19:in `load'
    from D:/Ruby192/bin/gollum:19:in `<main>'
```

Any ideas what could be wrong? Or isn't it even supposed to run under Windows? :-)

**Comment by jbcoder** [comment]
I'm not sure if anyone else was able to get this working on Windows. I tried installing it on a Windows 10 machine using the Windows architecture. It failed miserably. However, I got it up and running in no time using WSL. So, that's a good option now that Bash for Windows is here.

**Comment by dometto** [comment]
@jbcoder have you tried with jruby?

**Comment by jbcoder** [comment]
@dometto No, I haven't. But WSL seems to be doing the trick.

**Comment by rubin55** [comment]
For posterity, for those that come here trying to install Gollum on Windows, know that Gollum 4.x will never work on windows due to a dependency on posix-spawn, which, as of version 0.3.14 at least, does install on Windows, but does not work (you'll get a Type nil String error).

Version 5.x of Gollum moved to using rugged, which is tricky to install on Windows, but [it is possible](https://github.com/libgit2/rugged/issues/830#issuecomment-652962253). In the case of Gollum, as of this writing it specifically depends on rugged 0.99 which in turn specifically depends on libgit2 0.99; make sure to not upgrade your RIDK environment, because else you will get a newer libgit2. In any case, I imagine you can also download the package  from the MingW mirrors or find it in your pacman cache and `pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-libgit2-0.99.0-1-any.pkg.tar.xz`.

I'm *still* running into an issue related to rugged:

```
C:/PROGRA~1/RUBY/RUBY26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': 126: The specified module could not be found.   - C:/Users/rubin/.gem/ruby/2.6.0/gems/rugged-0.99.0/lib/rugged/rugged.so (LoadError)
```

I'm trying to find out why rugged can't be loaded.

**Comment by dometto** [comment]
Please note this bit from the Readme:

> Gollum runs on Unix-like systems using its adapter for rugged by default. You can also run Gollum on JRuby via its adapter for RJGit. On Windows, Gollum runs only on JRuby.

Just use the JRuby for Windows installer and `gem install gollum`.
