### ISSUE TITLE
When there simultaneous edits, there are no notifications or merging tools

### ISSUE THREAD

**Issue by huyl** [gollum/gollum#279]
If two users open the same page, and user A saves, and then user B saves,  A's changes are lost without notifying user B.

There should be at least some notification to user B and ideally an opportunity to merge the changes.

**Comment by 501st-alpha1** [comment]
Are there any updates on this issue? If not, I'm willing to work on it.

**Comment by dometto** [comment]
No updates, but PRs are very welcome! I suppose it would be best to implement this solely for the rugged adapter, which will be the default in the future. @501st-alpha1, I'm very willing to discuss implementations or help explain gollum's internal workings where necessary.

**Comment by 501st-alpha1** [comment]
Okay, thanks for the info! I may take you up on that offer. :P

**Comment by dometto** [comment]
@501st-alpha1, please do ;)

**Comment by dometto** [comment]
@501st-alpha1 it's been years but we'd like to solve this in the next major release, `v5.0`. If you still happen to be interested in working on this, that would be great! A simple implementation could work like this:

* User 1 edits page Foo. When he presses Save, a parameter is passed along with the POST request that contains the SHA-hash of the latest commit in which the page was changed when User 1 opened it for editing.
* In the [edit route](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L276) we first check if that is still the latest commit in which the page was updated.
  * If not, that means User 2 edited the page in the mean time. Display a dialog that gives User 1 this information and lets him choose to abort or overwrite User 1's changes.
  * In order to get that to work, the 'Save' button should use an Ajax call to update the page (and redirect to the updated page on success, or display a dialog otherwise)

That would solve a lot of the problem, but I don't know if there is still a deeper lying possibility of a race-condition, and what would be needed (some kind of locking) to prevent that. Any help welcome!

**Comment by ecksun** [comment]
I think commonly you use the `ETag` header together with `If-Match` to [detect mid-air collisions][0]

Basically only using those headers instead of handling it manually in the body.

[0]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#Avoiding_mid-air_collisions

**Comment by 501st-alpha1** [comment]
@dometto I don't think I ever got very far on this, and unfortunately I won't have time to work on this in the near future, so if you or someone else would like to take over, feel free.

Your suggested design sounds good.  I like the idea of instead using the SHA to set the parent commit (per https://github.com/gollum/gollum/issues/279#issuecomment-12734569) and allow the user to merge after (or better, auto-merge if possible), but I assume that would require more work.

**Comment by bartkamphorst** [comment]
Setting the `etag` header in `get '/edit/*'` (`app.rb`) is easy enough:
```ruby
etag(Digest::SHA1.hexdigest(@content))
```

However, sending the `If-Match` header with the post request is a little more tricky because we currently use plain HTML for sending the request. Since you [cannot send custom headers without javascript](https://stackoverflow.com/questions/3047711/custom-http-request-headers-in-html), getting this to work would require a rewrite of the submit code using javascript/jquery. The benefit is this is that the ajax call could subsequently have a callback for potential `Precondition Failed` errors (status code `412`), which signal editing conflicts.

**Comment by dometto** [comment]
Thanks for the research, @bartkamphorst! And yes, I think we'll have to use ajax for submission anyway in order to get a merge/discard handling dialog.

Quick question: couldn't we use the commit SHA id? Or would what end up being more expensive, since in case of a changed commit server-side we'd still have to determine of this specific file was touched by it?

**Comment by dometto** [comment]
Also, something similar should probably be implemented for the create route (it's possible that someone commits the page you want to create while you're writing it).

**Comment by bartkamphorst** [comment]
Actually, using `etag` headers presupposes that everything is handled with ajax, including the `edit` action. That is, currently, we cannot capture the etag header that is sent with the `get` request. So, while you are right about needing ajax submission for merging/discarding, I think we should go with a version of your original proposal instead. 👍 I think making the sha of the commit available as a hidden field in the `gollum-editor` form is probably the neatest way.

**Comment by bartkamphorst** [comment]
Detecting edit collisions is now implemented in `5.x` (see https://github.com/gollum/gollum/pull/1349). Currently, the user is only shown a warning notification, but the groundwork is there to expand this with some merging functionality.

I'm considering the bug as resolved, but I'll open a new improvement request issue for implementing the ability to merge two conflicting versions.
