### ISSUE TITLE
Parser not MathJax aware

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#449]
`$$a_{0,0} = a_{0,0}$$` is translated by [redcarpet](https://github.com/tanoku/redcarpet) as `<p>$$a<em>{0,0} = a</em>{0,0}$$</p>` which breaks MathJax.

**Comment by dometto** [comment]
Can't reproduce this with the latest gollum. It's been using `GitHub::Markdown` for markdown rendering for a while, apparently that *is* mathjax-aware.

**Comment by dometto** [comment]
The only markup I can still reproduce this problem with is orgmode: `_` are rendered by org as html `<sub>` tags, which breaks mathjax.

In order to fix this we would have to implement a Mathjax filter in the filter chain, and extract mathjax code blocks before rendering. We could do this for the standard `$$` and `\[` mathjax blocks, but then again, the user might have reconfigured these in her own mathjax config. So we should then also let the user configure the mathjax filter, in addition to mathjax itself.

**Comment by dometto** [comment]
The way to do this in Org mode is apparently to wrap the mathjax in the following block:
```org
#+BEGIN_HTML
$$a_{0,0} = a_{0,0}$$
#+END_HTML
```
This is apparently the supported way of using mathjax within org, so with that, it looks like all markups now support mathjax.

**Comment by bartkamphorst** [comment]
Cool. :+1:
