### ISSUE TITLE
Keyboard Shortcuts dialog

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#505]
As gollum now has keyboard shortcuts #496, it'd be nice to have an in app dialog that displays them all. The feature should mirror the .com behavior of Shift+?. Shift+? on any page will open the `Keyboard Shortcuts` dialog.

**Comment by dometto** [comment]
In `5.x` we've changed the default editor to `ace`, thanks to @ProgramFan. @ProgramFan, do you happen to know if there is an easy way to activate a dialog like this? All I can find is this list of shortcuts (which work in `5.x`): https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

And are custom gollum keyboard shortcuts still present/needed?

**Comment by ProgramFan** [comment]
After googling the topic, there is a dialog like that, and it is already bundled in ace, see https://ace.c9.io/demo/keyboard_shortcuts.html. I will create a PR for that.

For Gollum-only shortcuts, my experience shows that they do not work when the focus is in the editor area, but they work correctly when the focus leaves the editor. I think it is still necessary since they are convinient. We can add them back grandually.

**Comment by ProgramFan** [comment]
Addressed by PR #1229.

**Comment by dometto** [comment]
Thanks to @ProgramFan the shortcut dialog will finally be implemented in `v5.0`.
