### ISSUE TITLE
Unicode page name does not linked in internal link

### ISSUE THREAD

**Issue by majecty** [gollum/gollum#590]
I use gollum 2.4.0

I make link [[한글]] in '/home'
I clicked the link and make new page named 'hangeul' ( automatically it changed to ascii)

 When I reclicked the link [[한글]], Not the 'hangeul' page opened, But the '/create' page reopened. 

So I can't go to the 'hangeul' page by the wiki's internal link.

**Comment by dometto** [comment]
Unicode internal links are working properly when using the new [rugged adapter](https://github.com/gollum/rugged_adapter) (beta). When using grit, @bootstraponline's workaround is the only thing we can offer, due to the mentioned restrictions in grit. I'm closing this because no further fixes are forthcoming -- we will concentrate on improving the rugged adapter.
