### ISSUE TITLE
FTP links in Markdown are not properly rendered 

### ISSUE THREAD

**Issue by dmik** [gollum/gollum#759]
While making this page https://github.com/bitwiseworks/mozilla-os2/releases/tag/FIREFOX_17_0_5esr_RELEASE_OS2_Beta I surprisingly discovered that it's impossible to insert a clickable link to an FTP resource in the Markdown text field (applies to issues, comments, release notes, whatever). No matter if I use Markdown links or HTML directly, it always renders it to `<a>Text</a>`, w/o the `href` attribute:
- Markdown: [LIBC 0.6.5 Runtime](ftp://ftp.netlabs.org/pub/gcc/libc-0.6.5-csd5.zip)
- HTML <a href="ftp://ftp.netlabs.org/pub/gcc/libc-0.6.5-csd5.zip">LIBC 0.6.5 Runtime</a>

The source code of the above is:

```
* Markdown: [LIBC 0.6.5 Runtime] (ftp://ftp.netlabs.org/pub/gcc/libc-0.6.5-csd5.zip)
* HTML <a href="ftp://ftp.netlabs.org/pub/gcc/libc-0.6.5-csd5.zip">LIBC 0.6.5 Runtime</a>
```

This is kind of user-unfriendly since I have to ask people to copy & paste instead of clicking.

**Comment by svnpenn** [comment]
https://github.com/jch/html-pipeline/issues/187

**Comment by signalogic** [comment]
Looks like this issue is still alive in early 2017.  Is it the case that Github markdown, for some fundamental reason is different than other mark up/down languages, and cannot render a simple ftp link like:

  <a href="ftp://ftp.example.com">link description</a>

?  All we can get to work is Sunny's hack, above.

**Comment by svnpenn** [comment]
@signalogic the issue is @jch. His behavior has been questionable over the years. He essentially ignores his own repos.

- https://github.com/jch/html-pipeline/issues/192#issuecomment-148565499
- https://github.com/jch/html-pipeline/pull/39#issuecomment-72510219
- https://github.com/jch/html-pipeline/pull/104#issuecomment-93851203

Normally this would not be an issue, but:

1. He is a GitHub employee
2. The repos in question are critical infrastructure, being used by millions of people

**Comment by signalogic** [comment]
@svnpenn  Thanks for letting us know.  I'm sure Github guys are busy with many things, and this isn't a high priority item.

At least we know we're not doing something wrong with FTP link syntax.  Using a shortened link is a work-around, but I think security would be improved if Github users were not forced into frequent use of obscure links, and hopefully Github decision-makers can see that point.

**Comment by ricardoquesada** [comment]
another vote to fix this bug (still present August 2017)

**Comment by dometto** [comment]
Once again, this issue does not concern GitHub wikis. This is a different project. Please do not use this issue to complain about GitHub. For support contact them directly.

**Comment by IdoBar** [comment]
Another vote to fix this bug (still present April 2018)

**Comment by lrettig** [comment]
Still an issue in November 2018. Why is this issue closed?

**Comment by bartkamphorst** [comment]
If you would have taken the trouble to read through the issue, you would know why the issue is closed. I'm locking the conversation.
