### ISSUE TITLE
Support YAML front matter

### ISSUE THREAD

**Issue by trans** [gollum/gollum#774]
Working with Gollum in conjunction with static site generators I realized life would just be like a million times easier if Gollum gracefully handled YAML font-matter. Tons of static site generators have copied Jekyll's approach to this and Gollum makes a great way to edit content for simple CMS.

**Comment by SkyCrawl** [comment]
Parsing YAML front matter in the top of a page has already been implemented and tested in my fork of `gollum-lib` which will eventually turn into a PR. Details can be found [here](https://github.com/SkyCrawl/gollum-lib/blob/css-to-sass/TODO.md#whats-been-done).

**Comment by dometto** [comment]
Great work, let us know if we can help out! (will slowly start working on gollum again the coming days)

**Comment by SkyCrawl** [comment]
Thank you, @dometto . At this moment, my forks of both gollum and gollum-lib are still torn apart and I have to reorganize and put them back again, better than ever before I hope. But once I'm done with that, I would greatly appreciate help with several things :). Also it'll be a great time to discuss the changes I will have made and my future plans, so that we may avoid any potential missteps rather sooner than later...

**Comment by dometto** [comment]
Forthcoming in `5.x` (implemented in https://github.com/gollum/gollum/pull/1217)
