### ISSUE TITLE
Different paths in Renderer vs Preview?

### ISSUE THREAD

**Issue by pgraubner** [gollum/gollum#816]
Following situation in Gollum 2.7.0: 
+ My wiki has a subfolder "foo/"  and I am editing the page "foo/bar.md".
+ I am inserting an image located at "foo/1337.png" in my page with the __path relative to my wiki folder__: "foo/1337.png"
+ Preview renders image correctly
+ After saving the page, gollum tries to render the image __relative to my "foo/" folder__, i.e. "foo/foo/1337.png", resulting in a "Create New Page" for "1337 dot png" in folder "foo/foo".

**Comment by dometto** [comment]
I think the saved file is actually showing the correct behavior. Things are going accidentally as you expected in the preview, because the preview is assuming the page's location is the wiki's root. We should make sure the path of the page being edited is passed to `/preview`, and pass it on to gollum-lib's `Wiki#preview_page` method.

**Comment by pgraubner** [comment]
Hi, sorry for answering late. This issue was already solved in gollum/gollum-lib@9ea68040714e2f6c22a6e9832dda5617f5322014. Thanks for your help!

**Comment by bartkamphorst** [comment]
Thanks @pgraubner for letting us know!
