### ISSUE TITLE
Encoding::CompatibilityError at search Japanese words

### ISSUE THREAD

**Issue by soh-i** [gollum/gollum#830]
when trying to query words with specific Japanese character such as "トランス", "ト" or  "ミ", gollum throws  bellow the exception.
```
Encoding::CompatibilityError at /search
incompatible character encodings: UTF-8 and ASCII-8BIT
file: template.rb location: render line: 39
```

```
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-linux]
```

But the query  of "ア” (http:localhost:4557/search?q=ア) do not throws the Encoding error,  I'm complicated.

**Comment by dometto** [comment]
The remaining problem (forced transliteration of page names) is due to an issue in gollum (not in the underlying git backends). The transliteration is happening [here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L302) and [here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L278). The `.to_url` method (provided by the `stringex` gem) is forcing the page name to an ASCII transliteration.

I'm not sure what the best way to fix this is. `to_url` is being used to sanitize pagenames containing things like umlauts and interpunction; I'm not sure if we can simply leave that out. @jamieoliver, I've see you've worked a bit on the `to_url` stuff. Any thoughts on this?

**Comment by dometto** [comment]
Managed to override stringex's behavior so that the transliteration won't be forced: see https://github.com/gollum/gollum/pull/929. However, it turns out that there is still an underlying issue with grit: it will *create* files with utf-8 characters in the filename, but is apparently not detecting them. So #923 resolves this issue as far as possible: when using grit, transliteration will be forced, otherwise (when using the [rugged adapter](https://github.com/gollum/rugged_adapter), it will leave the utf-8 characters in place.
