### ISSUE TITLE
add Docker container to contrib/docker

### ISSUE THREAD

**Issue by schmunk42** [gollum/gollum#930]
Hi,

I created a [docker container for gollum](https://github.com/hrzg/docker-gollum), which may be useful for the contrib section. (continued from https://github.com/gollum/gollum/issues/843#issuecomment-68628396)
I'd like to hear some feedback, eg. if it is of general interest, if should should be included directly or as a submodule.

Looking forward to hear from you,
schmunk

**Comment by dometto** [comment]
I think it would be nice to have in `contrib`. :) Mostly I think the automatic push/pulling to `$REPO_URL` should be made explicit in the README, and there should be a contact e-mail and link to docs in the code that eventually gets merged. I think it would be useful to make the SSH-key bit optional, since people might just want to use a locally accessible repo. I think including it directly (no submodule) would probably be best, we can always pull in any important changes.

Thanks for considering working on this!

**Comment by schmunk42** [comment]
Did not forget you, but I have not much spare time at the moment, will get back to you in the next 14 days.

**Comment by bartkamphorst** [comment]
Sounds good; there's no rush. Thanks for letting us know!

**Comment by dometto** [comment]
@schmunk42, still interested in this?

**Comment by schmunk42** [comment]
To be honest ... I do not really have the time to complete this.
If someone else wants to accomplish a Docker setup for gollum, feel free to take my code as a base or restart from scratch. 
I am too involved in other projects, sorry.

**Comment by dometto** [comment]
No problem, @schmunk42. We'd be happy to receive any PRs for this, but it's not a priority, so I'll close the issue for now.
