### ISSUE TITLE
ERB support?

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#932]
We are using Gollum wiki to supplement a vendor's data dictionary (a set of database tables and a legacy `CHM` file).   

It would be nice to embed dynamic, database content into the wiki, perhaps akin to Rails `partials`.  The `include` directive could be expanded to support `partials`.

**Comment by dometto** [comment]
@craibuc I'm not sure I fully understand your proposal, since gollum is meant to run with a git repo as the backend, independently from a database. If you need access to a database yourself from the wiki, you could consider implementing this by means of a custom Macro: https://github.com/gollum/gollum/wiki/Macros
However, we wouldn't want to include anything that introduces database dependencies into gollum as such. Please let me know if I've misunderstood your proposal.

**Comment by dometto** [comment]
Ah, I didn't read the title of your issue, I think. Is the suggestion to enable rendering user-committed `.erb` partials? If so, I'd be worried about security: committing a `.erb` file would then basically allow any user to execute ruby code on the server.

Once again, if you'd want to implement this for your personal use case, a Macro could easily do the trick, I think.

**Comment by craibuc** [comment]
Looks easy enough.  Can this be simply added to the wiki's directory, or do I need to add it to gollum-lib's `macros

**Comment by dometto** [comment]
The latter (I see you got custom Macros working from your other post).
