### ISSUE TITLE
Include remote document?

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#935]
I'd like to include the 'raw' source of a document that is in a second wiki instance.  Use-case: one wiki is data dictionary, second wiki is code and documentation.

### Approach I
Use `include` directive with URL to the remote document's source:

    [[include:http://localhost:7890/remote-page.md]]

Which returned an error:
> Cannot include /http:/localhost:7890/request-9999.md) - does not exist yet

Approach II
Wrote a macro `IncludeRemote`:

```
require 'open-uri'

class Gollum::Macro::IncludeRemote < Gollum::Macro

  def render(url)

    $stdout.puts "#{self.class.name}(#{url})"

    begin

      open(url).read

    rescue Exception => e
      $stderr.puts "Error in macro #{self.class.name} - #{e.message}"

    end # begin

  end # def

end
```

Case I:
Macro references Markdown:

    <<IncludeRemote(http://localhost:7890/remote-page.md)>>

Result: Includes 'raw' Markdown content, but doesn't evaluate it.

Case II:
Macro references HTML:

    <<IncludeRemote(http://localhost:7890/remote-page)>>

Result: returns full wiki page (search page; new, edit buttons, etc).

Case III:
Markdown fed to `include` directive:

    [[include:<<IncludeRemote(http://localhost:7890/remote-page.md)>>]]

Result: `Cannot include` error.

Case IV:
HTML fed to `include` directive:

    [[include:<<IncludeRemote(http://localhost:7890/remote-page)>>]]

Result: same as II.

Is there a way to do this?

**Comment by dometto** [comment]
In the Macro approach, you need to use `Gollum::Markup` to render the raw markup that you're getting from `open(url).read`.
```ruby
raw_data = open(url).read
rendered = Gollum::Markup.new(nil).render_default(raw_data)
```
...or some such. See https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/markup.rb

Note that `#render_default` will not render Macros at the moment (not sure why). If you want that, you'll have to use `Markup#render`, which requires you to pass a `page` object to `Markup.new`. Since you don't have  a valid `Gollum::Page` instance, you could fake it with something like `OpenStruct`:

```ruby
page = OpenStruct.new(:wiki => @wiki, :filename => "blah", :text_data => raw_data, ...) # See Markup.new for which attributes you have to include
rendered = Gollum::Markup.new(page).render
```
