### ISSUE TITLE
Couple of bugs when running behind unicorn

### ISSUE THREAD

**Issue by f0o** [gollum/gollum#938]
Hi,

I'm trying to use gollum behind a unicorn and nginx.

It started out with a bunch of errors in sinatra where the method 'join' was unavailable for whatever reason..
But well, this got sorted out with a lot of googling and it works so far again. Cause is still unknown to be honest...

Now the next bug is that it redirects me from `http://domain.tld/` to `http://gollum/Home` - this is not the hostname being passed from nginx or it's canonical... Neither in config.rb, config.ru, unicorn.rb I've specified this and I dont see any option (generally I dont even find a complete list of available configuration-directives!) to configure this.

So here a couple of questions:

1. Is there any list of available configuration-directives?
2. Is there a readonly mode for gollum?
3. What's the preferred way of running gollum in production servers with HTTPS?
4. Is unicorn not supported for gollum?

Thanks,
f0o

//Edit: it seems like `#gollum` on freenode is empty... too bad...

//Edit2:
`./app.rb:103:      redirect clean_url(::File.join(@base_url, page_dir, wiki_new.index_page))`
seems to be the redirect that sends me to `http://gollum/Home`

//Edit3: Generally `ALL` redirects that gollum tries to do are failing...
I got the general impression that gollum is not meant for production and simply doesnt support unicorn..

**Comment by f0o** [comment]
Closing this because we're not using gollum anymore.

However, I do like the project! :+1:

**Comment by dometto** [comment]
> It started out with a bunch of errors in sinatra where the method 'join' was unavailable for whatever reason..

Hard to debug that without a stack trace. This must be caused by some underlying object being `nil`, which points to there being something wrong with your setup (although gollum should of course through a more descriptive error message). Possibly this is an instance of #100, which displays a similar error message.

> Is there any list of available configuration-directives?

The command-line [options](https://github.com/gollum/gollum#running) for `bin/gollum` are generally also configurable when mounting `Precious::App` in a `config.ru`. E.g. use `:h1_title => true` for --h1-title`.

> Is there a readonly mode for gollum?

`--no-edit` on the CLI corresponds to `:allow_editing => false` when setting the options in `config.ru`. Given the name mismatches between CLI options and the keys of the `wiki_options` hash, I agree that there should be a wiki page documenting these.

> What's the preferred way of running gollum in production servers with HTTPS?

I really have no opinion about what webserver to use in production. :) It shouldn't matter, as long as the rack-server (thin, unicorn, whatever) is functioning correctly, any problems with getting it to work with nginx or apache or whatever should be due to that webserver's configuration.

> Is unicorn not supported for gollum?

The aim is certainly to have it work with any rack compatible webserver. However, without more detail about your setup, it's hard to tell whether your issue is a gollum bug, or a problem with your configuration.

> ./app.rb:103: redirect clean_url(::File.join(@base_url, page_dir, wiki_new.index_page))
seems to be the redirect that sends me to http://gollum/Home

If `@base_url == 'gollum'` that would be a bug, I think. Can you try outputting that variable to debug? `$stderr.puts @base_url.inspect`

**Comment by dometto** [comment]
> Closing this because we're not using gollum anymore.

Fair enough. :+1: I documented the rack app options as you suggested, though:
https://github.com/gollum/gollum/wiki/Rack-app-options#the-options-hash

**Comment by f0o** [comment]
Thanks for the documentation, I'm sure someone will be very happy about it :+1: 

Will give gollum another try when time's on my side ;)
