### ISSUE TITLE
Supporting mindmap 

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#946]
Is it easy for extending gollum to support drawing mindmap? maybe the mindmap can be saved just as Markdown list? 

Some candidate may be:
* https://coggle.it
* http://naotu.baidu.com/
* http://my-mind.github.io/
* https://www.mindmup.com/

**Comment by dometto** [comment]
It's not trivial to extend gollum in this way. If you know of a pure ruby (or possibly JavaScript) mindmap implementation we could consider it. Note that it is possible to use graphs through Web Sequence Diagrams (we're thinking about a better solution for graphs, see #931).

**Comment by dometto** [comment]
The only option I see is to use https://github.com/bingwei/ruby-graphviz-mindmap. However, since that would require introducing a dependency on the graphviz binary, I don't think we want to include that into gollum. But someone could try using that to create a mindmap filter or macro for their own use.
